# Example queries for biological entities on COVID-19 Knowledge Graph
[Work in progress]

This notebook demonstrates how to run Cypher queries in a Jupyter Notebook by connecting to a database server.

In [1]:
import os
import time
import pandas as pd
from py2neo import Graph

In [2]:
pd.options.display.max_rows = None  # display all rows
pd.options.display.max_columns = None  # display all columsns

In [3]:
graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")

### List Node Metadata

In [4]:
query = """
MATCH (n:NodeMetadata)
RETURN n.name, n.shortDescription, n.description, n.example, n.details
"""
graph.run(query).to_data_frame()

Empty DataFrame
Columns: []
Index: []

### List Organisms in KG

In [5]:
query = """
MATCH (p:Organism)
RETURN p.name as name, p.scientificName as scientificName, p.id as taxonomy
"""
graph.run(query).to_data_frame()

,name,scientificName,taxonomy
0,SARS-CoV-2,Severe acute respiratory syndrome coronavirus 2,taxonomy:2697049
1,MERS-CoV,Middle East respiratory syndrome-related coron...,taxonomy:1335626
2,SARS-CoV,Severe acute respiratory syndrome-related coro...,taxonomy:694009
3,human,Homo sapiens,taxonomy:9606
4,intermediate horseshoe bat,Rhinolophus affinis,taxonomy:59477
5,Malayan horseshoe bat,Rhinolophus malayanus,taxonomy:608659
6,horseshoe bat,Rhinolophus,taxonomy:49442
7,Malayan pangolin,Manis javanica,taxonomy:9974
8,palm civet,Paradoxurus,taxonomy:71116
9,carnivores,Canidae,taxonomy:9608
10,cat,Felis catus,taxonomy:9685
11,European mink,Mustela lutreola,taxonomy:9666
12,Malayan tiger,Panthera tigris jacksoni,taxonomy:419130

### List Coronavirus Outbreaks

In [6]:
query = """
MATCH (p:Organism)-[:CAUSES]->(o:Outbreak)
RETURN p.name as name, p.scientificName as scientificName, p.id as taxonomy, o.id as outbreak, o.startDate as startDate
"""
graph.run(query).to_data_frame()

,name,scientificName,taxonomy,outbreak,startDate
0,SARS-CoV-2,Severe acute respiratory syndrome coronavirus 2,taxonomy:2697049,COVID-19,2019
1,MERS-CoV,Middle East respiratory syndrome-related coron...,taxonomy:1335626,MERS,2012
2,SARS-CoV,Severe acute respiratory syndrome-related coro...,taxonomy:694009,SARS,2003

### List Strains that are mentioned in PubMed Central Articles

In [7]:
query = """
MATCH (p:Publication)-[:MENTIONS]->(s:Strain)<-[:CARRIES]-(o:Organism)
RETURN p.id as pmc, s.name as name, s.collectionDate  as collectionDate, o.name as host, s.id as host_id
ORDER by s.collectionDate
"""
graph.run(query).to_data_frame().head(20)

,pmc,name,collectionDate,host,host_id
0,pmc:PMC7106203,BetaCoV/Wuhan/IPBCAMS-WH-01/2019,2019-12-24,human,https://www.gisaid.org/EPI_ISL_402123
1,pmc:PMC7147275,BetaCoV/Wuhan/IPBCAMS-WH-01/2019,2019-12-24,human,https://www.gisaid.org/EPI_ISL_402123
2,pmc:PMC7108203,BetaCoV/Wuhan/IPBCAMS-WH-01/2019,2019-12-24,human,https://www.gisaid.org/EPI_ISL_402123
3,pmc:PMC7192074,BetaCoV/Wuhan/IPBCAMS-WH-01/2019,2019-12-24,human,https://www.gisaid.org/EPI_ISL_402123
4,pmc:PMC7184472,BetaCoV/Wuhan/IPBCAMS-WH-01/2019,2019-12-24,human,https://www.gisaid.org/EPI_ISL_402123
5,pmc:PMC7106203,BetaCoV/Wuhan/WH-01/2019,2019-12-26,human,https://www.gisaid.org/EPI_ISL_406798
6,pmc:PMC7156227,Wuhan-Hu-1,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402125
7,pmc:PMC7211182,WIV02,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402127
8,pmc:PMC7233248,Wuhan-Hu-1,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402125
9,pmc:PMC7106203,WIV05,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402128
10,pmc:PMC7166825,Wuhan-Hu-1,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402125
11,pmc:PMC7106203,WIV02,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402127
12,pmc:PMC7102556,WIV04,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402124
13,pmc:PMC7106203,BetaCoV/Wuhan/IPBCAMS-WH-03/2019,2019-12-30,human,https://www.gisaid.org/EPI_ISL_403930
14,pmc:PMC7152513,WIV04,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402124
15,pmc:PMC7106203,BetaCoV/Wuhan/HBCDC-HB-01/2019,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402132
16,pmc:PMC7048180,WIV04,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402124
17,pmc:PMC7106203,WIV07,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402130
18,pmc:PMC7092803,BetaCoV/Wuhan/IVDC-HB-05/2019,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402121
19,pmc:PMC7166309,WIV06,2019-12-30,human,https://www.gisaid.org/EPI_ISL_402129

### List Gene and Protein information for Reference Genome
This query lists the genes and proteins encoded by the SARS-CoV-2 reference genome. This is the first genome of SARS-CoV-2 collected in Wuhan on Dec. 5, 2019.

In [8]:
query = """
MATCH (s:Strain)-[:HAS]->(g:Gene)-[:ENCODES]->(p:Protein)
RETURN s.id as referenceGenome, s.name as name, s.collectionDate  as collectionDate, 
       g.name as gene, g.id as geneId, p.name as protein, p.id as protein_id 
ORDER by s.collectionDate
"""
graph.run(query).to_data_frame()

Empty DataFrame
Columns: []
Index: []

### Find Mutations in the SARS-CoV-2 "S" gene
The S gene is translated by the human or other species to the spike protein, which binds the human ACE2 receptor to gain entrance into the cell. Here we compare the mutations (missense mutations) found at different locations.

In [43]:
query = """
MATCH (g:Gene{name:'S'})-[:HAS_VARIANT]->(v:Variant{variantConsequence:'missense_variant'})
<-[:HAS_VARIANT]-(s:Strain)-[:FOUND_IN]->(l:Location)-[:IN*]->(r:USRegion{name:$region}) 
RETURN v.name AS mutation, l.name AS location, r.name AS region
ORDER BY v.name, l.name
"""

##### Variants in the US West Region

In [44]:
region = 'West Region'
graph.run(query, region=region).to_data_frame().head(100)

           mutation           location       region
0   S:c.1042Gca>Aca         Washington  West Region
1   S:c.1042Gca>Aca         Washington  West Region
2   S:c.1151cCt>cTt        King County  West Region
3   S:c.1151cCt>cTt          San Diego  West Region
4   S:c.1153Act>Gct  Washington County  West Region
5   S:c.1183Gtc>Atc          San Diego  West Region
6   S:c.1214gAt>gTt            Arizona  West Region
7   S:c.1240Caa>Gaa            Arizona  West Region
8   S:c.1240Caa>Gaa            Arizona  West Region
9   S:c.1240Caa>Gaa            Arizona  West Region
10  S:c.1240Caa>Gaa            Arizona  West Region
11  S:c.1240Caa>Gaa            Arizona  West Region
12  S:c.1240Caa>Gaa            Arizona  West Region
13  S:c.1241cAa>cCa            Arizona  West Region
14    S:c.13Ctt>Ttt            Arizona  West Region
15    S:c.13Ctt>Ttt             Nevada  West Region
16    S:c.13Ctt>Ttt             Nevada  West Region
17    S:c.13Ctt>Ttt      Pierce County  West Region
18    S:c.13Ctt>Ttt      Pierce County  West Region
19    S:c.13Ctt>Ttt      Pierce County  West Region
20    S:c.13Ctt>Ttt      Pierce County  West Region
21    S:c.13Ctt>Ttt      Pierce County  West Region
22    S:c.13Ctt>Ttt      Skagit County  West Region
23    S:c.13Ctt>Ttt         Washington  West Region
24    S:c.13Ctt>Ttt         Washington  West Region
25    S:c.13Ctt>Ttt      Yakima County  West Region
26    S:c.13Ctt>Ttt      Yakima County  West Region
27    S:c.13Ctt>Ttt      Yakima County  West Region
28    S:c.13Ctt>Ttt      Yakima County  West Region
29    S:c.13Ctt>Ttt      Yakima County  West Region
30    S:c.13Ctt>Ttt      Yakima County  West Region
31  S:c.1424gCc>gTc            Arizona  West Region
32  S:c.1424gCc>gTc            Arizona  West Region
33  S:c.1426Ggt>Agt              Idaho  West Region
34  S:c.1426Ggt>Agt              Idaho  West Region
35  S:c.1426Ggt>Agt             Oregon  West Region
36  S:c.1426Ggt>Agt             Oregon  West Region
37  S:c.1426Ggt>Agt   Snohomish County  West Region
38  S:c.1426Ggt>Agt   Snohomish County  West Region
39  S:c.1426Ggt>Agt         Washington  West Region
40  S:c.1426Ggt>Agt         Washington  West Region
41  S:c.1448gTt>gCt        King County  West Region
42  S:c.1448gTt>gCt        King County  West Region
43  S:c.1448gTt>gCt        King County  West Region
44  S:c.1448gTt>gCt        King County  West Region
45  S:c.1448gTt>gCt        King County  West Region
46  S:c.1448gTt>gCt        King County  West Region
47  S:c.1448gTt>gCt        King County  West Region
48  S:c.1448gTt>gCt        King County  West Region
49  S:c.1448gTt>gCt   Snohomish County  West Region
50  S:c.1448gTt>gCt   Snohomish County  West Region
51  S:c.1448gTt>gCt         Washington  West Region
52  S:c.1448gTt>gCt         Washington  West Region
53  S:c.1448gTt>gCt         Washington  West Region
54  S:c.1448gTt>gCt         Washington  West Region
55  S:c.1448gTt>gCt         Washington  West Region
56  S:c.1448gTt>gCt         Washington  West Region
57  S:c.1448gTt>gCt         Washington  West Region
58  S:c.1448gTt>gCt         Washington  West Region
59  S:c.1448gTt>gCt         Washington  West Region
60  S:c.1448gTt>gCt         Washington  West Region
61  S:c.1448gTt>gCt         Washington  West Region
62  S:c.1448gTt>gCt         Washington  West Region
63  S:c.1448gTt>gCt         Washington  West Region
64  S:c.1448gTt>gCt         Washington  West Region
65   S:c.145Cat>Tat         California  West Region
66   S:c.145Cat>Tat         California  West Region
67  S:c.1557caT>caA         Washington  West Region
68  S:c.1557caT>caA         Washington  West Region
69  S:c.1558Gca>Tca             Alaska  West Region
70  S:c.1558Gca>Tca        King County  West Region
71  S:c.1558Gca>Tca        King County  West Region
72  S:c.1558Gca>Tca        King County  West Region
73  S:c.1558Gca>Tca         Washington  West Region
74  S:c.1558Gca>Tca         Washington  West Region
75  S:c.1558Gca>Tca         Washington  West Region
76  S:c.1558Gca>Tca         Washington  West Region
77  S:c.1565gCa>gTa        King County  West Region
78   S:c.162ttG>ttC              Idaho  West Region
79   S:c.162ttG>ttC              Idaho  West Region
80   S:c.162ttG>ttT       Adams County  West Region
81   S:c.162ttG>ttT       Adams County  West Region
82  S:c.1640aCa>aTa        King County  West Region
83  S:c.1658aCt>aTt         California  West Region
84  S:c.1658aCt>aTt      San Francisco  West Region
85  S:c.1715aCt>aTt          San Diego  West Region
86  S:c.1841gAt>gGt       Adams County  West Region
87  S:c.1841gAt>gGt             Alaska  West Region
88  S:c.1841gAt>gGt             Alaska  West Region
89  S:c.1841gAt>gGt             Alaska  West Region
90  S:c.1841gAt>gGt             Alaska  West Region
91  S:c.1841gAt>gGt             Alaska  West Region
92  S:c.1841gAt>gGt             Alaska  West Region
93  S:c.1841gAt>gGt             Alaska  West Region
94  S:c.1841gAt>gGt             Alaska  West Region
95  S:c.1841gAt>gGt             Alaska  West Region
96  S:c.1841gAt>gGt             Alaska  West Region
97  S:c.1841gAt>gGt             Alaska  West Region
98  S:c.1841gAt>gGt             Alaska  West Region
99  S:c.1841gAt>gGt             Alaska  West Region

##### Variants in the US Northeast Region

In [51]:
region = 'Northeast Region'
graph.run(query, region=region).to_data_frame().head(100)

           mutation       location            region
0   S:c.1076aGc>aAc         Queens  Northeast Region
1   S:c.1150Cct>Tct         Queens  Northeast Region
2   S:c.1150Cct>Tct         Queens  Northeast Region
3     S:c.13Ctt>Ttt       Brooklyn  Northeast Region
4     S:c.13Ctt>Ttt       Brooklyn  Northeast Region
5     S:c.13Ctt>Ttt       Brooklyn  Northeast Region
6     S:c.13Ctt>Ttt  Hudson County  Northeast Region
7     S:c.13Ctt>Ttt      Manhattan  Northeast Region
8     S:c.13Ctt>Ttt  Nassau County  Northeast Region
9     S:c.13Ctt>Ttt  Nassau County  Northeast Region
10    S:c.13Ctt>Ttt  Nassau County  Northeast Region
11    S:c.13Ctt>Ttt  Nassau County  Northeast Region
12    S:c.13Ctt>Ttt       New York  Northeast Region
13    S:c.13Ctt>Ttt       New York  Northeast Region
14    S:c.13Ctt>Ttt         Queens  Northeast Region
15    S:c.13Ctt>Ttt  Staten Island  Northeast Region
16  S:c.1501Aat>Tat         Queens  Northeast Region
17  S:c.1507Gtt>Ttt       Brooklyn  Northeast Region
18  S:c.1558Gca>Tca       Brooklyn  Northeast Region
19  S:c.1586aAg>aGg     Pittsburgh  Northeast Region
20   S:c.162ttG>ttT         Queens  Northeast Region
21  S:c.1662gaG>gaT      Manhattan  Northeast Region
22  S:c.1708Gct>Act         Queens  Northeast Region
23  S:c.1749gaG>gaT      Manhattan  Northeast Region
24  S:c.1749gaG>gaT      Manhattan  Northeast Region
25  S:c.1841gAt>gGt  Albany County  Northeast Region
26  S:c.1841gAt>gGt  Bergen County  Northeast Region
27  S:c.1841gAt>gGt  Bergen County  Northeast Region
28  S:c.1841gAt>gGt  Bergen County  Northeast Region
29  S:c.1841gAt>gGt  Bergen County  Northeast Region
30  S:c.1841gAt>gGt  Bergen County  Northeast Region
31  S:c.1841gAt>gGt       Brooklyn  Northeast Region
32  S:c.1841gAt>gGt       Brooklyn  Northeast Region
33  S:c.1841gAt>gGt       Brooklyn  Northeast Region
34  S:c.1841gAt>gGt       Brooklyn  Northeast Region
35  S:c.1841gAt>gGt       Brooklyn  Northeast Region
36  S:c.1841gAt>gGt       Brooklyn  Northeast Region
37  S:c.1841gAt>gGt       Brooklyn  Northeast Region
38  S:c.1841gAt>gGt       Brooklyn  Northeast Region
39  S:c.1841gAt>gGt       Brooklyn  Northeast Region
40  S:c.1841gAt>gGt       Brooklyn  Northeast Region
41  S:c.1841gAt>gGt       Brooklyn  Northeast Region
42  S:c.1841gAt>gGt       Brooklyn  Northeast Region
43  S:c.1841gAt>gGt       Brooklyn  Northeast Region
44  S:c.1841gAt>gGt       Brooklyn  Northeast Region
45  S:c.1841gAt>gGt       Brooklyn  Northeast Region
46  S:c.1841gAt>gGt       Brooklyn  Northeast Region
47  S:c.1841gAt>gGt       Brooklyn  Northeast Region
48  S:c.1841gAt>gGt       Brooklyn  Northeast Region
49  S:c.1841gAt>gGt       Brooklyn  Northeast Region
50  S:c.1841gAt>gGt       Brooklyn  Northeast Region
51  S:c.1841gAt>gGt       Brooklyn  Northeast Region
52  S:c.1841gAt>gGt       Brooklyn  Northeast Region
53  S:c.1841gAt>gGt       Brooklyn  Northeast Region
54  S:c.1841gAt>gGt       Brooklyn  Northeast Region
55  S:c.1841gAt>gGt       Brooklyn  Northeast Region
56  S:c.1841gAt>gGt       Brooklyn  Northeast Region
57  S:c.1841gAt>gGt       Brooklyn  Northeast Region
58  S:c.1841gAt>gGt       Brooklyn  Northeast Region
59  S:c.1841gAt>gGt       Brooklyn  Northeast Region
60  S:c.1841gAt>gGt       Brooklyn  Northeast Region
61  S:c.1841gAt>gGt       Brooklyn  Northeast Region
62  S:c.1841gAt>gGt       Brooklyn  Northeast Region
63  S:c.1841gAt>gGt       Brooklyn  Northeast Region
64  S:c.1841gAt>gGt       Brooklyn  Northeast Region
65  S:c.1841gAt>gGt       Brooklyn  Northeast Region
66  S:c.1841gAt>gGt       Brooklyn  Northeast Region
67  S:c.1841gAt>gGt       Brooklyn  Northeast Region
68  S:c.1841gAt>gGt       Brooklyn  Northeast Region
69  S:c.1841gAt>gGt       Brooklyn  Northeast Region
70  S:c.1841gAt>gGt       Brooklyn  Northeast Region
71  S:c.1841gAt>gGt       Brooklyn  Northeast Region
72  S:c.1841gAt>gGt       Brooklyn  Northeast Region
73  S:c.1841gAt>gGt       Brooklyn  Northeast Region
74  S:c.1841gAt>gGt       Brooklyn  Northeast Region
75  S:c.1841gAt>gGt       Brooklyn  Northeast Region
76  S:c.1841gAt>gGt       Brooklyn  Northeast Region
77  S:c.1841gAt>gGt       Brooklyn  Northeast Region
78  S:c.1841gAt>gGt       Brooklyn  Northeast Region
79  S:c.1841gAt>gGt       Brooklyn  Northeast Region
80  S:c.1841gAt>gGt       Brooklyn  Northeast Region
81  S:c.1841gAt>gGt       Brooklyn  Northeast Region
82  S:c.1841gAt>gGt       Brooklyn  Northeast Region
83  S:c.1841gAt>gGt       Brooklyn  Northeast Region
84  S:c.1841gAt>gGt       Brooklyn  Northeast Region
85  S:c.1841gAt>gGt       Brooklyn  Northeast Region
86  S:c.1841gAt>gGt       Brooklyn  Northeast Region
87  S:c.1841gAt>gGt       Brooklyn  Northeast Region
88  S:c.1841gAt>gGt       Brooklyn  Northeast Region
89  S:c.1841gAt>gGt       Brooklyn  Northeast Region
90  S:c.1841gAt>gGt       Brooklyn  Northeast Region
91  S:c.1841gAt>gGt       Brooklyn  Northeast Region
92  S:c.1841gAt>gGt       Brooklyn  Northeast Region
93  S:c.1841gAt>gGt       Brooklyn  Northeast Region
94  S:c.1841gAt>gGt       Brooklyn  Northeast Region
95  S:c.1841gAt>gGt       Brooklyn  Northeast Region
96  S:c.1841gAt>gGt       Brooklyn  Northeast Region
97  S:c.1841gAt>gGt       Brooklyn  Northeast Region
98  S:c.1841gAt>gGt       Brooklyn  Northeast Region
99  S:c.1841gAt>gGt       Brooklyn  Northeast Region

### Cases in a specific County (Admin2)

In [30]:
admin2 = 'San Diego County'

query = """
MATCH (c:Cases{date: date("2020-06-03")})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cummulativeConfirmed as confirmed, c.cummulativeDeaths as deaths
"""
graph.run(query, admin2=admin2).to_data_frame()

               name  confirmed  deaths
0  San Diego County       7674     276

### Aggregate cases by State (Admin1)

In [33]:
query = """
MATCH (o:Outbreak{id: "COVID-19"})<-[:RELATED_TO]-(c:Cases{date: date("2020-06-03")})-[:REPORTED_IN]->(a:Admin2)-[:IN]->(a1:Admin1)
RETURN a1.name as state, sum(c.cummulativeDeaths) as deaths, sum(c.cummulativeConfirmed) as confirmed
ORDER BY deaths DESC
"""
graph.run(query).to_data_frame()

             state  deaths  confirmed
0         New York   30019     374085
1       New Jersey   11880     161608
2    Massachusetts    7139     101231
3     Pennsylvania    5742      77780
4         Illinois    5531     122395
5         Michigan    5450      53277
6       California    4331     116735
7      Connecticut    3989      42843
8          Florida    2529      57898
9             None    2415      47574
10       Louisiana    2311      35888
11            Ohio    2300      36792
12        Maryland    2295      48645
13         Georgia    2092      45373
14         Indiana    1997      34392
15           Texas    1744      68877
16        Colorado    1494      27046
17        Virginia    1146      36366
18      Washington    1135      22456
19       Minnesota    1072      25678
20  North Carolina     999      31276
21         Arizona     980      22356
22     Mississippi     774      15763
23         Alabama     650      18423
24       Wisconsin     616      19303
25            Iowa     574      20300
26  South Carolina     501      12415
27        Kentucky     450      10402
28          Nevada     429       8951
29       Tennessee     384      24246
30        Delaware     375       9659
31      New Mexico     372       7285
32        Oklahoma     341       6805
33   New Hampshire     265       4785
34          Kansas     226      10092
35          Oregon     159       4399
36        Arkansas     141       7131
37        Nebraska     135      14670
38        Missouri     122       4883
39            Utah     104       9293
40           Maine      95       2414
41           Idaho      83       2933
42   West Virginia      78       2077
43    North Dakota      66       2679
44    South Dakota      62       5162
45         Vermont      55        985
46          Hawaii      17        643
47         Montana      17        525
48          Alaska      10        504
49         Wyoming       1        915
50    Rhode Island       0      13071