# Downloads Demographic data from the American Community Survey

**[Work in progress]**

This notebook demographic data estimates (DP05) from the American Community Survey 5-Year Data (2009-2018).

Data source: [American Community Survey 5-Year Data (2009-2018)](https://www.census.gov/data/developers/data-sets/acs-5year.html)

Authors: Peter Rose (pwrose@ucsd.edu), Ilya Zaslavsky (zaslavsk@sdsc.edu)

In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
pd.options.display.max_rows = None  # display all rows
pd.options.display.max_columns = None  # display all columsns

In [3]:
NEO4J_IMPORT = Path(os.getenv('NEO4J_IMPORT'))
print(NEO4J_IMPORT)

/Users/peter/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-19636412-9e74-4bac-8a4c-c6c8b49bb9d3/installation-4.1.0/import

## Download selected fields

[List of variables as HTML](https://api.census.gov/data/2018/acs/acs5/profile/groups/DP05.html) or [JSON](https://api.census.gov/data/2018/acs/acs5/profile/groups/DP05/)

[Example URLs for API](https://api.census.gov/data/2018/acs/acs5/profile/examples.html)

### Add variables and names here (names must use Neo4j property naming conventions)

The numbers in each subgroup below adds up to the total population

In [4]:
variables = {'DP05_0001E': 'totalPopulation',
             
             # sex
             'DP05_0002E': 'male',
             'DP05_0003E': 'female',
             
             # age
             'DP05_0005E': 'age0_4',
             'DP05_0006E': 'age5_9',
             'DP05_0007E': 'age10_14',
             'DP05_0008E': 'age15_19',
             'DP05_0009E': 'age20_24',
             'DP05_0010E': 'age25_34',
             'DP05_0011E': 'age35_44',
             'DP05_0012E': 'age45_54',
             'DP05_0013E': 'age55_59',
             'DP05_0014E': 'age60_64',
             'DP05_0015E': 'age65_74',
             'DP05_0016E': 'age75_84',
             'DP05_0017E': 'age85_',

              # race
             'DP05_0037E': 'white',
             'DP05_0038E': 'blackOrAfricanAmerican',
             'DP05_0039E': 'americanIndianAndAlaskaNative',
             'DP05_0044E': 'asian',
             'DP05_0052E': 'nativeHawaiianAndOtherPacificIslander',
             'DP05_0057E': 'otherRace',
             'DP05_0058E': 'twoOrMoreRaces',
             
              # hispanic or latino
             'DP05_0071E': 'hispanicOrLatino',
             'DP05_0076E': 'notHispanicOrLatino'
            }

In [5]:
fields = ",".join(variables.keys())

## Download county-level data using UC Census API

In [6]:
url_county = f'https://api.census.gov/data/2018/acs/acs5/profile?get={fields}&for=county:*'

In [7]:
df = pd.read_json(url_county, dtype='str')
df.fillna('', inplace=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
0,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,DP05_0009E,DP05_0010E,DP05_0011E,DP05_0012E,DP05_0013E,DP05_0014E,DP05_0015E,DP05_0016E,DP05_0017E,DP05_0037E,DP05_0038E,DP05_0039E,DP05_0044E,DP05_0052E,DP05_0057E,DP05_0058E,DP05_0071E,DP05_0076E,state,county
1,47086,22018,25068,3614,3107,3554,3152,3351,5844,5236,5760,3224,3291,4282,1961,710,12097,33982,56,282,0,391,278,729,46357,28,151
2,12028,5845,6183,728,776,806,849,671,1279,1562,1602,786,897,1247,589,236,9475,2368,0,17,0,16,152,181,11847,28,111
3,8321,4174,4147,458,564,486,598,416,866,921,1092,536,644,979,547,214,5631,2596,23,15,8,13,35,33,8288,28,019
4,23480,11821,11659,1262,1439,1506,1919,1670,2753,2830,3142,1519,1435,2250,1181,574,21346,1681,75,57,7,170,144,360,23120,28,057

##### Add column names

In [8]:
df = df[1:].copy() # skip first row of labels
columns = list(variables.values())
columns.append('stateFips')
columns.append('countyFips')
df.columns = columns

In [9]:
df.head()

,totalPopulation,male,female,age0_4,age5_9,age10_14,age15_19,age20_24,age25_34,age35_44,age45_54,age55_59,age60_64,age65_74,age75_84,age85_,white,blackOrAfricanAmerican,americanIndianAndAlaskaNative,asian,nativeHawaiianAndOtherPacificIslander,otherRace,twoOrMoreRaces,hispanicOrLatino,notHispanicOrLatino,stateFips,countyFips
1,47086,22018,25068,3614,3107,3554,3152,3351,5844,5236,5760,3224,3291,4282,1961,710,12097,33982,56,282,0,391,278,729,46357,28,151
2,12028,5845,6183,728,776,806,849,671,1279,1562,1602,786,897,1247,589,236,9475,2368,0,17,0,16,152,181,11847,28,111
3,8321,4174,4147,458,564,486,598,416,866,921,1092,536,644,979,547,214,5631,2596,23,15,8,13,35,33,8288,28,019
4,23480,11821,11659,1262,1439,1506,1919,1670,2753,2830,3142,1519,1435,2250,1181,574,21346,1681,75,57,7,170,144,360,23120,28,057
5,10129,5116,5013,455,467,740,803,416,812,1212,1390,962,623,1353,726,170,6523,3503,6,0,0,0,97,29,10100,28,015

In [10]:
# Example data
df[(df['stateFips'] == '06') & (df['countyFips'] == '073')]

,totalPopulation,male,female,age0_4,age5_9,age10_14,age15_19,age20_24,age25_34,age35_44,age45_54,age55_59,age60_64,age65_74,age75_84,age85_,white,blackOrAfricanAmerican,americanIndianAndAlaskaNative,asian,nativeHawaiianAndOtherPacificIslander,otherRace,twoOrMoreRaces,hispanicOrLatino,notHispanicOrLatino,stateFips,countyFips
1869,3302833,1661931,1640902,211969,198148,197726,209496,262118,541385,436855,420221,201666,183654,251516,127904,60175,2335447,166412,20980,390418,13903,205307,170366,1106925,2195908,06,073

In [11]:
df['source'] = 'American Community Survey 5 year'
df['aggregationLevel'] = 'Admin2'

In [21]:
states = list(df['stateFips'].unique())
states.sort()

In [27]:
df[(df['stateFips'] == '06')]

,totalPopulation,male,female,age0_4,age5_9,age10_14,age15_19,age20_24,age25_34,age35_44,age45_54,age55_59,age60_64,age65_74,age75_84,age85_,white,blackOrAfricanAmerican,americanIndianAndAlaskaNative,asian,nativeHawaiianAndOtherPacificIslander,otherRace,twoOrMoreRaces,hispanicOrLatino,notHispanicOrLatino,stateFips,countyFips
1855,64148,31879,32269,3683,3828,3496,3516,3231,6973,6706,8097,5137,5540,8591,3975,1375,49463,1562,2426,661,30,8048,1958,12830,51318,06,033
1856,17540,8920,8620,762,761,751,804,803,1885,1614,2284,1503,1683,2778,1556,356,15579,166,397,243,54,396,705,1909,15631,06,043
1857,75493,38468,37025,6126,5796,5815,4955,5600,11930,9193,8410,4592,4001,5647,2311,1117,56344,2432,1079,5104,343,4126,6065,20990,54503,06,115
1858,1133247,553701,579546,65505,73025,76328,72857,68013,143793,151683,164203,78858,69200,99537,48565,21680,648325,97333,5529,185065,5585,112976,78434,288101,845146,06,013
1859,31185,20671,10514,1384,1272,1477,1444,3218,6287,4353,3899,1803,1891,2504,1250,403,25672,2738,877,437,205,590,666,5834,25351,06,035
1860,443738,222208,221530,28356,27457,27240,37445,49425,58974,50124,49960,25886,24096,35041,19841,9893,344026,8626,4389,23863,814,42024,19996,200060,243678,06,083
1861,501317,245196,256121,25736,28607,28944,29922,30140,65417,61766,66429,35686,37573,55520,23956,11621,375519,7960,4854,20087,1636,63422,27839,132985,368332,06,097
1862,180216,92250,87966,15092,13588,14616,13576,14006,26210,21833,20565,9536,8748,12428,6979,3039,115817,4591,1801,2684,419,47362,7542,151019,29197,06,025
1863,14174,7341,6833,464,786,911,630,1341,2264,1563,1964,1314,907,1385,568,77,12017,105,527,339,0,801,385,3866,10308,06,051
1864,1643700,807171,836529,97506,96428,95792,93865,103705,271867,244557,224507,106455,93101,126820,60948,28149,681725,177135,10712,486434,13768,169771,104155,369061,1274639,06,001
1865,1510023,737742,772281,99356,101293,102000,94932,100159,234363,197732,195044,95111,87826,117908,57619,26680,875793,149064,10340,235474,16715,115072,107565,347025,1162998,06,067
1866,140530,70082,70448,7318,7449,9619,9036,8888,17269,17769,18925,9560,9337,14353,7545,3462,102711,2867,1198,11373,272,16738,5371,47687,92843,06,055
1867,433212,220967,212245,32318,31786,32230,30473,31877,63216,56042,51701,25456,22598,32072,15291,8152,256709,11200,3221,24342,2011,117386,18343,252588,180624,06,053
1868,2930,1542,1388,112,111,153,141,83,187,380,254,482,174,516,281,56,2890,6,25,0,0,0,9,324,2606,06,091
1869,3302833,1661931,1640902,211969,198148,197726,209496,262118,541385,436855,420221,201666,183654,251516,127904,60175,2335447,166412,20980,390418,13903,205307,170366,1106925,2195908,06,073
1870,214977,104375,110602,12467,12618,13052,20389,30396,29455,24981,23778,11704,10696,14761,7050,3630,145778,5834,1247,29612,984,17774,13748,67809,147168,06,113
1871,135768,67666,68102,7364,7787,6803,9105,12763,18345,17028,15030,9122,9774,14208,5791,2648,108784,1585,6797,4160,436,5778,8228,15360,120408,06,023
1872,1146,612,534,39,58,79,114,72,91,140,83,68,109,192,66,35,723,9,311,8,8,0,87,105,1041,06,003
1873,87422,43439,43983,5143,5838,4704,5160,4778,9969,10119,10569,6405,6892,11538,4309,1998,73121,531,3591,1689,170,4020,4300,21679,65743,06,045
1874,273765,135727,138038,14535,14511,15516,22731,27607,33557,31870,34702,19532,18203,25867,10581,4553,208476,2596,1375,12601,316,35546,12855,91676,182089,06,087
1875,10098052,4976788,5121264,624745,607905,626594,654903,738416,1609935,1387454,1369838,631221,547764,734393,384700,180184,5186859,823987,70527,1469968,27929,2121102,397680,4893603,5204449,06,037
1876,2383286,1186188,1197098,158008,169403,177796,177697,170153,328917,303627,303884,142066,123126,186772,101900,39937,1450134,153545,19281,152130,6843,495241,106112,1154517,1228769,06,065
1877,1922200,970469,951731,118688,119462,124678,113909,121662,304906,280977,269412,120020,101578,138006,75122,33780,865460,48058,9303,689176,7541,205997,96665,495455,1426745,06,085
1878,260295,127113,133182,12292,15188,16044,14371,11859,22746,31827,41362,20429,19552,32032,15888,6705,203342,5709,737,15000,584,22262,12661,41335,218960,06,041
1879,43540,21706,21834,2257,2695,2309,2459,2028,4439,4286,5085,3768,3751,6451,2829,1183,36971,632,1469,678,149,719,2922,5336,38204,06,093
1880,179085,87859,91226,10520,10893,10500,10808,10213,22779,19093,22249,12939,13470,20852,10598,4171,155840,2209,4704,5427,191,3415,7299,17605,161480,06,089
1881,27424,14575,12849,1584,1547,1849,1533,1474,4081,3448,3370,2151,1802,2808,1166,611,20958,785,2024,977,17,968,1695,5340,22084,06,015
1882,27897,14171,13726,2051,1760,2347,2031,1784,3447,3385,3382,1652,1758,2445,1363,492,23127,255,670,820,51,2416,558,11504,16393,06,021
1883,227075,112513,114562,12523,13858,11572,15615,25617,28693,24065,25068,15004,14841,23163,11730,5326,186095,3477,2885,10151,427,9890,14150,36358,190717,06,007
1884,18699,9423,9276,859,893,827,992,698,1714,1844,2211,1592,2081,3160,1410,418,16654,194,428,200,41,464,718,1629,17070,06,063
1885,281455,142769,138686,13457,14079,14326,22464,29568,32771,30037,32501,19546,19948,31047,15299,6412,242078,5265,1900,10234,258,11581,10139,63002,218453,06,079
1886,883053,452646,430407,71173,72357,72906,65963,68554,135500,110974,102382,49204,42035,55461,26402,10142,663592,48179,9488,41842,1698,87118,31136,465842,417211,06,029
1887,3164182,1562429,1601753,188956,189548,206380,208793,218993,453121,415919,453608,211722,176654,249211,131180,60097,1950902,54732,14466,635672,9442,370679,128289,1080195,2083987,06,059
1888,45235,22434,22801,1936,2398,1926,2319,2054,3929,4212,5878,3966,4403,7469,3517,1228,41375,302,492,568,126,547,1825,5297,39938,06,009
1889,95872,47789,48083,6614,7219,7031,6583,6204,13284,11641,11722,5701,5645,7826,4618,1784,66752,2006,936,14635,569,4435,6539,29354,66518,06,101
1890,765935,377851,388084,44775,46334,43978,40654,42295,111996,110088,108983,51530,47435,66210,33971,17686,391024,17849,2922,215337,10504,85574,42725,189002,576933,06,081
1891,53932,28102,25830,2389,2833,2220,2641,2726,6669,5563,6359,4214,4967,7859,3739,1753,47189,926,997,749,134,1432,2505,6527,47405,06,109
1892,732212,364612,367600,52723,57384,56988,55240,51640,101222,94351,92011,42250,38942,52720,25773,10968,411958,52023,4725,112997,4463,71360,74686,301256,430956,06,077
1893,37829,20302,17527,1534,1540,1727,1978,1530,3744,4329,5105,3003,3387,6144,2555,1253,32989,790,305,499,73,1374,1799,5132,32697,06,005
3024,269075,135816,133259,21254,22886,22499,23338,21064,38509,32974,30749,14281,12201,16993,8987,3340,154376,8772,1988,20131,623,72152,11033,158494,110581,06,047
3025,8938,4613,4325,402,556,464,491,252,1115,873,1050,691,751,1351,690,252,8046,149,298,140,6,52,247,1292,7646,06,049
3026,18085,9084,9001,1011,1108,888,1055,779,2047,2018,2120,1404,1507,2321,1247,580,14557,161,2101,290,35,322,619,3927,14158,06,027
3027,539301,266844,272457,39410,41234,41604,39283,37852,77347,67919,66531,33381,26970,39540,19925,8305,408817,15534,4261,29248,3973,54861,22607,245973,293328,06,099
3028,63373,31504,31869,3867,4283,4463,3872,3554,7538,7003,8006,4489,4333,7013,3481,1471,54119,471,1621,964,19,3639,2540,15623,47750,06,103
3029,59416,29626,29790,3902,4187,4678,4469,4104,7890,7645,8149,3850,3348,4278,2031,885,48851,440,422,1739,117,5035,2812,35248,24168,06,069
3030,186661,93040,93621,8672,10025,11954,11579,9715,18743,20562,26817,16226,15617,22676,10245,3830,164202,1494,1268,8291,406,4051,6949,23631,163030,06,017
3031,870044,443970,426074,39519,31072,29588,30492,49822,202928,137296,115998,51067,50824,71250,38978,21210,406538,45402,2746,297667,2911,67424,47356,132651,737393,06,075
3032,460477,230255,230222,38504,40849,40772,37292,33987,64943,57243,51482,23979,21035,29507,14406,6478,352259,7326,5469,16462,697,62743,15521,295149,165328,06,107
3033,99092,48889,50203,4221,4656,5063,5249,4126,9903,10823,11994,8407,9473,15491,6588,3098,91579,655,864,1008,154,1379,3453,9281,89811,06,057
3034,155013,74683,80330,11807,11847,12193,11303,10848,21466,19585,18065,8898,8204,12760,5764,2273,111621,5026,2505,3294,169,26944,5454,88806,66207,06,039
3035,12862,6582,6280,571,646,523,752,404,1057,1418,1661,1076,1365,2067,1055,267,11136,87,577,207,158,377,320,930,11932,06,105
3036,2135413,1062472,1072941,154616,159351,160376,159896,169422,319211,273918,268397,128278,108605,141854,66406,25083,1305047,178404,17894,149837,6506,376608,101117,1127813,1007600,06,071
3037,380077,185511,194566,20325,25051,24540,24399,20279,41834,48667,52916,26116,24851,40466,21867,8766,313636,6197,1890,27535,839,11920,18060,52498,327579,06,061
3038,438530,217931,220599,26706,27649,27594,26976,29952,63551,54436,58247,29377,29652,39080,17772,7538,231149,61826,2114,67813,4113,39952,31563,114406,324124,06,095
3039,21464,11124,10340,1589,1708,1639,1538,1356,2878,2523,2641,1494,1132,1768,860,338,18854,362,201,324,53,1112,558,12655,8809,06,011
3040,150075,82674,67401,11639,11665,11255,10441,12754,25059,20610,18001,7714,6370,8414,4632,1521,98429,9687,2291,5946,337,26971,6414,81154,68921,06,031
3041,978130,487936,490194,78636,78627,78151,71970,74241,148512,120605,111792,53835,47323,66238,32360,15840,627437,47372,10961,100017,1770,151250,39323,515907,462223,06,019
3042,848112,419588,428524,51709,53476,59175,57639,59428,112151,105619,116202,59504,49774,71153,35016,17266,680197,14835,7069,61772,1771,44907,37561,360017,488095,06,111

### Save data

In [12]:
df.to_csv(NEO4J_IMPORT / "03a-USCensusDP05Admin2.csv", index=False)

## Download zip-level data using UC Census API

In [13]:
url_zip = f'https://api.census.gov/data/2018/acs/acs5/profile?get={fields}&for=zip%20code%20tabulation%20area:*'

In [14]:
df = pd.read_json(url_zip, dtype='str')
df.fillna('', inplace=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,DP05_0009E,DP05_0010E,DP05_0011E,DP05_0012E,DP05_0013E,DP05_0014E,DP05_0015E,DP05_0016E,DP05_0017E,DP05_0037E,DP05_0038E,DP05_0039E,DP05_0044E,DP05_0052E,DP05_0057E,DP05_0058E,DP05_0071E,DP05_0076E,zip code tabulation area
1,8642,4312,4330,567,430,453,532,344,901,975,1226,843,745,916,522,188,8226,256,2,21,0,0,137,27,8615,43964
2,51116,23286,27830,3438,3367,3204,4094,3740,7553,8183,7607,2628,2225,2958,1577,542,13583,32929,25,1054,0,2274,1251,4077,47039,28216
3,71605,33421,38184,4222,5769,5767,4563,2944,8540,11786,11186,5117,4079,5063,1842,727,51272,6346,200,10533,0,978,2276,5172,66433,28277
4,27286,12870,14416,2277,1988,1861,1812,1339,4140,4488,3950,1806,1336,1593,533,163,14515,8672,7,1709,53,590,1740,2870,24416,28278

##### Add column names

In [15]:
df = df[1:].copy() # skip first row
columns = list(variables.values())
columns.append('postalCode')
df.columns = columns

In [16]:
df.head()

,totalPopulation,male,female,age0_4,age5_9,age10_14,age15_19,age20_24,age25_34,age35_44,age45_54,age55_59,age60_64,age65_74,age75_84,age85_,white,blackOrAfricanAmerican,americanIndianAndAlaskaNative,asian,nativeHawaiianAndOtherPacificIslander,otherRace,twoOrMoreRaces,hispanicOrLatino,notHispanicOrLatino,postalCode
1,8642,4312,4330,567,430,453,532,344,901,975,1226,843,745,916,522,188,8226,256,2,21,0,0,137,27,8615,43964
2,51116,23286,27830,3438,3367,3204,4094,3740,7553,8183,7607,2628,2225,2958,1577,542,13583,32929,25,1054,0,2274,1251,4077,47039,28216
3,71605,33421,38184,4222,5769,5767,4563,2944,8540,11786,11186,5117,4079,5063,1842,727,51272,6346,200,10533,0,978,2276,5172,66433,28277
4,27286,12870,14416,2277,1988,1861,1812,1339,4140,4488,3950,1806,1336,1593,533,163,14515,8672,7,1709,53,590,1740,2870,24416,28278
5,29414,13958,15456,2144,1784,1542,1504,2318,5357,3591,2955,1842,1673,2610,1406,688,14358,11486,187,1185,132,345,1721,3084,26330,28303

In [17]:
# Example data
df.query("postalCode == '92130'")

,totalPopulation,male,female,age0_4,age5_9,age10_14,age15_19,age20_24,age25_34,age35_44,age45_54,age55_59,age60_64,age65_74,age75_84,age85_,white,blackOrAfricanAmerican,americanIndianAndAlaskaNative,asian,nativeHawaiianAndOtherPacificIslander,otherRace,twoOrMoreRaces,hispanicOrLatino,notHispanicOrLatino,postalCode
30726,55316,27583,27733,3310,4310,4405,4428,2178,5868,9178,10243,4149,2557,3166,1250,274,33966,1382,177,16573,9,623,2586,3999,51317,92130

In [18]:
df['source'] = 'American Community Survey 5 year'
df['aggregationLevel'] = 'PostalCode'

### Save data

In [19]:
df.to_csv(NEO4J_IMPORT / "03a-USCensusDP05Zip.csv", index=False)