# Example queries for Case Counts on COVID-19 Knowledge Graph
[Work in progress]

This notebook demonstrates how to run Cypher queries to retrieve and aggregate COVID-19 case counts.

COVID-19 case numbers are provided by:

Country and US County level data: [JHU](https://github.com/covid-19-net/covid-19-community/blob/master/reference_data/DataProvider.csv#L6)

San Diego data by zip code: [SDHHSA](https://github.com/covid-19-net/covid-19-community/blob/master/reference_data/DataProvider.csv#L7)

In [1]:
import datetime
import pandas as pd
from py2neo import Graph

In [2]:
pd.options.display.max_rows = None  # display all rows
pd.options.display.max_columns = None  # display all columsns

#### Connect to COVID-19-Net Knowledge Graph

In [3]:
graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")

In [4]:
# currently defining "yesterday" as two days from current date, 
# since there are time periods during the day, where data from the 
# previous day are not yet available in UTC date.
today = datetime.datetime.utcnow().date()
yesterday = today - datetime.timedelta(days=2)

## COVID Case Data

### Case counts by Country

In [5]:
query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(n:Country)
RETURN n.name, c.cases, c.deaths, c.date as dateUTC
ORDER by n.name
"""
graph.run(query, day=yesterday).to_data_frame()

,n.name,c.cummulativeConfirmed,c.cummulativeDeaths,dateUTC
0,Afghanistan,38143,1402,2020-08-29
1,Albania,9279,275,2020-08-29
2,Algeria,43781,1491,2020-08-29
3,Andorra,1124,53,2020-08-29
4,Angola,2551,107,2020-08-29
5,Anguilla,3,0,2020-08-29
6,Antigua and Barbuda,94,3,2020-08-29
7,Argentina,401239,8353,2020-08-29
8,Armenia,43626,872,2020-08-29
9,Aruba,1975,10,2020-08-29
10,Austria,26985,733,2020-08-29
11,Azerbaijan,36174,529,2020-08-29
12,Bahamas,2135,50,2020-08-29
13,Bahrain,51391,189,2020-08-29
14,Bangladesh,308925,4206,2020-08-29
15,Barbados,170,7,2020-08-29
16,Belarus,71523,671,2020-08-29
17,Belgium,84599,9891,2020-08-29
18,Belize,964,13,2020-08-29
19,Benin,2145,40,2020-08-29
20,Bermuda,169,9,2020-08-29
21,Bhutan,195,0,2020-08-29
22,Bolivia,115354,4938,2020-08-29
23,Bosnia and Herzegovina,19550,594,2020-08-29
24,Botswana,1562,3,2020-08-29
25,Brazil,3846153,120262,2020-08-29
26,British Virgin Islands,35,1,2020-08-29
27,Brunei,144,3,2020-08-29
28,Bulgaria,16164,605,2020-08-29
29,Burkina Faso,1352,55,2020-08-29
30,Burundi,445,1,2020-08-29
31,Cabo Verde,3778,39,2020-08-29
32,Cambodia,273,0,2020-08-29
33,Cameroon,19142,411,2020-08-29
34,Cayman Islands,205,1,2020-08-29
35,Central African Republic,4700,61,2020-08-29
36,Chad,1008,77,2020-08-29
37,Chile,408009,11181,2020-08-29
38,Colombia,599884,19063,2020-08-29
39,Comoros,423,7,2020-08-29
40,Costa Rica,39699,418,2020-08-29
41,Croatia,9861,183,2020-08-29
42,Cuba,3925,94,2020-08-29
43,Curacao,62,1,2020-08-29
44,Cyprus,1483,20,2020-08-29
45,Czechia,24094,421,2020-08-29
46,Democratic Republic of the Congo,10007,258,2020-08-29
47,Denmark,16779,624,2020-08-29
48,Djibouti,5385,60,2020-08-29
49,Dominica,20,0,2020-08-29
50,Dominican Republic,93732,1673,2020-08-29
51,Ecuador,112906,6537,2020-08-29
52,Egypt,98497,5376,2020-08-29
53,El Salvador,25537,708,2020-08-29
54,Equatorial Guinea,4941,83,2020-08-29
55,Eritrea,318,0,2020-08-29
56,Estonia,2363,64,2020-08-29
57,Eswatini,4510,91,2020-08-29
58,Ethiopia,49654,770,2020-08-29
59,Falkland Islands,13,0,2020-08-29
60,Faroe Islands,411,0,2020-08-29
61,Fiji,28,2,2020-08-29
62,Finland,8049,335,2020-08-29
63,France,288531,30460,2020-08-29
64,French Guiana,9076,58,2020-08-29
65,French Polynesia,482,0,2020-08-29
66,Gabon,8505,53,2020-08-29
67,Gambia,2895,96,2020-08-29
68,Georgia,1462,19,2020-08-29
69,Germany,242835,9299,2020-08-29
70,Ghana,44118,270,2020-08-29
71,Gibraltar,275,0,2020-08-29
72,Greece,9977,260,2020-08-29
73,Greenland,14,0,2020-08-29
74,Grenada,24,0,2020-08-29
75,Guadeloupe,1145,16,2020-08-29
76,Guatemala,73679,2728,2020-08-29
77,Guernsey,625,48,2020-08-29
78,Guinea,9251,59,2020-08-29
79,Guinea-Bissau,2205,34,2020-08-29
80,Guyana,1184,35,2020-08-29
81,Haiti,8174,201,2020-08-29
82,Honduras,59645,1842,2020-08-29
83,Hong Kong,4786,87,2020-08-29
84,Hungary,5669,614,2020-08-29
85,Iceland,2100,10,2020-08-29
86,India,3542733,63498,2020-08-29
87,Indonesia,169195,7261,2020-08-29
88,Iran,371816,21359,2020-08-29
89,Iraq,227446,6891,2020-08-29
90,Ireland,28720,1777,2020-08-29
91,Isle of Man,336,24,2020-08-29
92,Israel,113465,906,2020-08-29
93,Italy,266853,35473,2020-08-29
94,Ivory Coast,17893,115,2020-08-29
95,Jamaica,2113,20,2020-08-29
96,Japan,67353,1271,2020-08-29
97,Jordan,1893,15,2020-08-29
98,Kazakhstan,105684,1523,2020-08-29
99,Kenya,33794,572,2020-08-29
100,Kosovo,12683,488,2020-08-29
101,Kuwait,84224,528,2020-08-29
102,Kyrgyzstan,43712,1057,2020-08-29
103,Laos,22,0,2020-08-29
104,Latvia,1381,34,2020-08-29
105,Lebanon,16275,155,2020-08-29
106,Lesotho,1051,31,2020-08-29
107,Liberia,1304,82,2020-08-29
108,Libya,12958,231,2020-08-29
109,Liechtenstein,107,1,2020-08-29
110,Lithuania,2839,86,2020-08-29
111,Luxembourg,6625,124,2020-08-29
112,Madagascar,14791,190,2020-08-29
113,Malawi,5528,174,2020-08-29
114,Malaysia,9317,125,2020-08-29
115,Maldives,7578,28,2020-08-29
116,Mali,2757,126,2020-08-29
117,Malta,1847,10,2020-08-29
118,Martinique,596,16,2020-08-29
119,Mauritania,7012,158,2020-08-29
120,Mauritius,355,10,2020-08-29
121,Mayotte,3301,40,2020-08-29
122,Mexico,591712,63819,2020-08-29
123,Moldova,36404,990,2020-08-29
124,Monaco,154,4,2020-08-29
125,Mongolia,301,0,2020-08-29
126,Montenegro,4727,93,2020-08-29
127,Montserrat,13,1,2020-08-29
128,Morocco,60056,1078,2020-08-29
129,Mozambique,3760,22,2020-08-29
130,Myanmar,749,6,2020-08-29
131,Namibia,7116,69,2020-08-29
132,Nepal,37340,207,2020-08-29
133,Netherlands,69632,6224,2020-08-29
134,New Caledonia,23,0,2020-08-29
135,New Zealand,1729,22,2020-08-29
136,Nicaragua,4494,137,2020-08-29
137,Niger,1175,69,2020-08-29
138,Nigeria,53727,1011,2020-08-29
139,North Macedonia,14293,596,2020-08-29
140,Norway,10611,264,2020-08-29
141,Oman,85005,650,2020-08-29
142,Pakistan,295372,6284,2020-08-29
143,Palestinian Territory,21668,147,2020-08-29
144,Panama,91337,1983,2020-08-29
145,Papua New Guinea,453,5,2020-08-29
146,Paraguay,16474,294,2020-08-29
147,Peru,629961,28471,2020-08-29
148,Philippines,213131,3419,2020-08-29
149,Poland,66239,2032,2020-08-29
150,Portugal,57448,1818,2020-08-29
151,Qatar,118407,196,2020-08-29
152,Republic of the Congo,3979,78,2020-08-29
153,Reunion,1557,6,2020-08-29
154,Romania,85833,3539,2020-08-29
155,Russia,982573,16977,2020-08-29
156,Rwanda,3843,16,2020-08-29
157,Saint Barthelemy,18,0,2020-08-29
158,Saint Kitts and Nevis,17,0,2020-08-29
159,Saint Lucia,26,0,2020-08-29
160,Saint Martin,213,5,2020-08-29
161,Saint Pierre and Miquelon,5,0,2020-08-29
162,Saint Vincent and the Grenadines,60,0,2020-08-29
163,San Marino,710,42,2020-08-29
164,Sao Tome and Principe,895,15,2020-08-29
165,Saudi Arabia,313911,3840,2020-08-29
166,Senegal,13456,282,2020-08-29
167,Serbia,31282,710,2020-08-29
168,Seychelles,136,0,2020-08-29
169,Sierra Leone,2019,70,2020-08-29
170,Singapore,56717,27,2020-08-29
171,Sint Maarten,444,17,2020-08-29
172,Slovakia,3842,33,2020-08-29
173,Slovenia,2834,133,2020-08-29
174,Somalia,3310,97,2020-08-29
175,South Africa,622551,13981,2020-08-29
176,South Korea,19699,323,2020-08-29
177,South Sudan,2519,47,2020-08-29
178,Spain,439286,29011,2020-08-29
179,Sri Lanka,2995,12,2020-08-29
180,Sudan,13189,823,2020-08-29
181,Suriname,3954,67,2020-08-29
182,Sweden,83958,5821,2020-08-29
183,Switzerland,41722,2005,2020-08-29
184,Syria,2628,106,2020-08-29
185,Taiwan,488,7,2020-08-29
186,Tajikistan,8516,68,2020-08-29
187,Tanzania,509,21,2020-08-29
188,Thailand,3411,58,2020-08-29
189,Timor Leste,27,0,2020-08-29
190,Togo,1390,27,2020-08-29
191,Trinidad and Tobago,1645,19,2020-08-29
192,Tunisia,3572,76,2020-08-29
193,Turkey,267064,6284,2020-08-29
194,Turks and Caicos Islands,490,3,2020-08-29
195,Uganda,2847,29,2020-08-29
196,Ukraine,119751,2540,2020-08-29
197,United Arab Emirates,69328,379,2020-08-29
198,United Kingdom,332752,41498,2020-08-29
199,United States,5961094,182761,2020-08-29
200,Uruguay,1570,44,2020-08-29
201,Uzbekistan,41067,307,2020-08-29
202,Vatican,12,0,2020-08-29
203,Venezuela,44946,375,2020-08-29
204,Vietnam,1040,32,2020-08-29
205,Western Sahara,10,1,2020-08-29
206,Yemen,1946,563,2020-08-29
207,Zambia,11902,284,2020-08-29
208,Zimbabwe,6406,196,2020-08-29

### Case counts by US States aggregated from US Counties
Note, some counties in the Johns Hopkins dataset cannot be mapped to US counties. They are listed in as "None"

In [6]:
query = """
MATCH (c:Cases{date: $date, source: 'JHU'})-[:REPORTED_IN]->(a:Admin2)-[:IN]->(a1:Admin1)
RETURN a1.name as state, a1.code, a1.location, sum(c.deaths) as deaths, sum(c.cases) as confirmed, c.date as date
ORDER BY a1.code
"""
graph.run(query, date=yesterday).to_data_frame()

,state,a1.code,a1.location,deaths,confirmed,date
0,Alaska,AK,"(-150.00028, 64.00028)",37,5180,2020-08-29
1,Alabama,AL,"(-86.75026, 32.75041)",2059,115284,2020-08-29
2,Arkansas,AR,"(-92.50044, 34.75037)",772,59477,2020-08-29
3,Arizona,AZ,"(-111.50098, 34.5003)",5006,201287,2020-08-29
4,California,CA,"(-119.75126, 37.25022)",12894,702038,2020-08-29
5,Colorado,CO,"(-105.50083, 39.00027)",1942,57020,2020-08-29
6,Connecticut,CT,"(-72.66648, 41.66704)",4465,52391,2020-08-29
7,District of Columbia,DC,"(-77.00025, 38.91706)",605,13925,2020-08-29
8,Delaware,DE,"(-75.49992, 39.00039)",604,17071,2020-08-29
9,Florida,FL,"(-82.5001, 28.75054)",11105,618019,2020-08-29
10,Georgia,GA,"(-83.50018, 32.75042)",5447,249140,2020-08-29
11,Hawaii,HI,"(-156.38612, 20.78785)",61,8115,2020-08-29
12,Iowa,IA,"(-93.50049, 42.00027)",1100,63601,2020-08-29
13,Idaho,ID,"(-114.25118, 44.5002)",358,31665,2020-08-29
14,Illinois,IL,"(-89.25037, 40.00032)",8008,231287,2020-08-29
15,Indiana,IN,"(-86.25027, 40.00032)",3066,92434,2020-08-29
16,Kansas,KS,"(-98.50063, 38.50029)",449,41595,2020-08-29
17,Kentucky,KY,"(-84.87762, 38.20042)",921,47577,2020-08-29
18,Louisiana,LA,"(-92.0004, 31.00047)",4741,146056,2020-08-29
19,Massachusetts,MA,"(-71.10832, 42.36565)",9030,117886,2020-08-29
20,Maryland,MD,"(-76.74997, 39.00039)",3734,107294,2020-08-29
21,Maine,ME,"(-69.24977, 45.50032)",132,4489,2020-08-29
22,Michigan,MI,"(-85.50033, 44.25029)",6637,105646,2020-08-29
23,Minnesota,MN,"(-94.25055, 46.25024)",1814,74112,2020-08-29
24,Missouri,MO,"(-92.50046, 38.25031)",1459,74059,2020-08-29
25,Mississippi,MS,"(-89.75036, 32.75041)",2427,82029,2020-08-29
26,Montana,MT,"(-109.75102, 47.00025)",104,7251,2020-08-29
27,North Carolina,NC,"(-80.00032, 35.50069)",2683,165076,2020-08-29
28,North Dakota,ND,"(-100.00068, 47.50027)",141,11484,2020-08-29
29,Nebraska,NE,"(-99.75067, 41.50028)",391,33631,2020-08-29
30,New Hampshire,NH,"(-71.4998, 43.66702)",432,7243,2020-08-29
31,New Jersey,NJ,"(-74.49987, 40.16706)",15933,190983,2020-08-29
32,New Mexico,NM,"(-106.00085, 34.50034)",769,23858,2020-08-29
33,Nevada,NV,"(-116.75119, 39.25021)",1302,68461,2020-08-29
34,New York,NY,"(-75.4999, 43.00035)",32938,433402,2020-08-29
35,Ohio,OH,"(-83.00018, 40.25034)",4252,121320,2020-08-29
36,Oklahoma,OK,"(-97.50328, 35.49209)",797,57250,2020-08-29
37,Oregon,OR,"(-120.50139, 44.00013)",454,26293,2020-08-29
38,Pennsylvania,PA,"(-77.7, 40.8)",7656,137576,2020-08-29
39,Rhode Island,RI,"(-71.49978, 41.75038)",0,19809,2020-08-29
40,South Carolina,SC,"(-81.00009, 34.00043)",2698,117249,2020-08-29
41,South Dakota,SD,"(-100.25069, 44.50026)",167,12942,2020-08-29
42,Tennessee,TN,"(-86.25027, 35.75035)",1694,145966,2020-08-29
43,Texas,TX,"(-99.25061, 31.25044)",12607,626751,2020-08-29
44,Utah,UT,"(-111.75103, 39.25024)",335,41130,2020-08-29
45,Virginia,VA,"(-77.44675, 37.54812)",2568,118794,2020-08-29
46,Vermont,VT,"(-72.74983, 44.00034)",58,1597,2020-08-29
47,Washington,WA,"(-120.50147, 47.50012)",1901,73612,2020-08-29
48,Wisconsin,WI,"(-90.00041, 44.50024)",1119,74800,2020-08-29
49,West Virginia,WV,"(-80.50009, 38.50038)",215,9970,2020-08-29
50,Wyoming,WY,"(-107.5009, 43.00024)",1,3722,2020-08-29

### Current cases in San Diego County

In [7]:
admin2 = 'San Diego County'

query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cases as confirmed, c.deaths as deaths, c.date as date
"""
graph.run(query, admin2=admin2, day=yesterday).to_data_frame()

               name  confirmed  deaths        date
0  San Diego County      38047     679  2020-08-29

### COVID-19 Cases Time Series in San Diego County

In [8]:
query = """
MATCH (c:Cases{source: 'JHU'})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cases as confirmed, c.deaths as deaths, c.date as date
ORDER BY c.date DESC
"""
graph.run(query, admin2=admin2).to_data_frame()

                 name  confirmed  deaths        date
0    San Diego County      38300     682  2020-08-30
1    San Diego County      38047     679  2020-08-29
2    San Diego County      37784     676  2020-08-28
3    San Diego County      37499     673  2020-08-27
4    San Diego County      37222     668  2020-08-26
5    San Diego County      36994     665  2020-08-25
6    San Diego County      36727     660  2020-08-24
7    San Diego County      36540     660  2020-08-23
8    San Diego County      36203     660  2020-08-22
9    San Diego County      35912     652  2020-08-21
10   San Diego County      35608     644  2020-08-20
11   San Diego County      35376     638  2020-08-19
12   San Diego County      34960     626  2020-08-18
13   San Diego County      34678     626  2020-08-17
14   San Diego County      34344     626  2020-08-16
15   San Diego County      34065     622  2020-08-15
16   San Diego County      34065     622  2020-08-14
17   San Diego County      33393     608  2020-08-13
18   San Diego County      33157     602  2020-08-12
19   San Diego County      32975     594  2020-08-11
20   San Diego County      32975     594  2020-08-10
21   San Diego County      32330     593  2020-08-09
22   San Diego County      31779     586  2020-08-08
23   San Diego County      31127     583  2020-08-07
24   San Diego County      31127     583  2020-08-06
25   San Diego County      30516     568  2020-08-05
26   San Diego County      30516     568  2020-08-04
27   San Diego County      29883     565  2020-08-03
28   San Diego County      29883     565  2020-08-02
29   San Diego County      29048     561  2020-08-01
30   San Diego County      29048     561  2020-07-31
31   San Diego County      28688     558  2020-07-30
32   San Diego County      28287     552  2020-07-29
33   San Diego County      27507     533  2020-07-28
34   San Diego County      27507     533  2020-07-27
35   San Diego County      26701     533  2020-07-26
36   San Diego County      26098     524  2020-07-25
37   San Diego County      26098     524  2020-07-24
38   San Diego County      25608     512  2020-07-23
39   San Diego County      25107     505  2020-07-22
40   San Diego County      24520     487  2020-07-21
41   San Diego County      24135     478  2020-07-20
42   San Diego County      23682     478  2020-07-19
43   San Diego County      23114     478  2020-07-18
44   San Diego County      21855     465  2020-07-17
45   San Diego County      21855     465  2020-07-16
46   San Diego County      21446     448  2020-07-15
47   San Diego County      20887     436  2020-07-14
48   San Diego County      19929     422  2020-07-13
49   San Diego County      19371     422  2020-07-12
50   San Diego County      19371     422  2020-07-11
51   San Diego County      18863     420  2020-07-10
52   San Diego County      18402     415  2020-07-09
53   San Diego County      17842     406  2020-07-08
54   San Diego County      17578     399  2020-07-07
55   San Diego County      16726     387  2020-07-06
56   San Diego County      16726     387  2020-07-05
57   San Diego County      15696     387  2020-07-04
58   San Diego County      15696     387  2020-07-03
59   San Diego County      15207     377  2020-07-02
60   San Diego County      14623     370  2020-07-01
61   San Diego County      14149     365  2020-06-30
62   San Diego County      13832     361  2020-06-29
63   San Diego County      13334     361  2020-06-28
64   San Diego County      12837     360  2020-06-27
65   San Diego County      12401     358  2020-06-26
66   San Diego County      11961     352  2020-06-25
67   San Diego County      11626     347  2020-06-24
68   San Diego County      11294     341  2020-06-23
69   San Diego County      11096     338  2020-06-22
70   San Diego County      10794     338  2020-06-21
71   San Diego County      10484     338  2020-06-20
72   San Diego County      10350     332  2020-06-19
73   San Diego County      10092     331  2020-06-18
74   San Diego County       9730     323  2020-06-17
75   San Diego County       9730     323  2020-06-16
76   San Diego County       9610     320  2020-06-15
77   San Diego County       9440     319  2020-06-14
78   San Diego County       9314     319  2020-06-13
79   San Diego County       8998     308  2020-06-12
80   San Diego County       8998     308  2020-06-11
81   San Diego County       8837     305  2020-06-10
82   San Diego County       8619     296  2020-06-09
83   San Diego County       8619     296  2020-06-08
84   San Diego County       8345     296  2020-06-07
85   San Diego County       8345     296  2020-06-06
86   San Diego County       7940     288  2020-06-05
87   San Diego County       7798     283  2020-06-04
88   San Diego County       7674     276  2020-06-03
89   San Diego County       7554     269  2020-06-02
90   San Diego County       7481     269  2020-06-01
91   San Diego County       7481     269  2020-05-31
92   San Diego County       7385     269  2020-05-30
93   San Diego County       7100     260  2020-05-29
94   San Diego County       7100     260  2020-05-28
95   San Diego County       6882     249  2020-05-27
96   San Diego County       6797     249  2020-05-26
97   San Diego County       6701     249  2020-05-25
98   San Diego County       6559     249  2020-05-24
99   San Diego County       6559     249  2020-05-23
100  San Diego County       6315     241  2020-05-22
101  San Diego County       6140     230  2020-05-21
102  San Diego County       6140     230  2020-05-20
103  San Diego County       6026     222  2020-05-19
104  San Diego County       5836     209  2020-05-18
105  San Diego County       5836     209  2020-05-17
106  San Diego County       5662     209  2020-05-16
107  San Diego County       5391     200  2020-05-15
108  San Diego County       5391     200  2020-05-14
109  San Diego County       5161     190  2020-05-13
110  San Diego County       5161     190  2020-05-12
111  San Diego County       5065     175  2020-05-11
112  San Diego County       4776     175  2020-05-10
113  San Diego County       4662     169  2020-05-09
114  San Diego County       4429     165  2020-05-08
115  San Diego County       4319     158  2020-05-07
116  San Diego County       4319     158  2020-05-06
117  San Diego County       4020     144  2020-05-05
118  San Diego County       3927     139  2020-05-04
119  San Diego County       3927     139  2020-05-03
120  San Diego County       3711     134  2020-05-02
121  San Diego County       3564     124  2020-05-01
122  San Diego County       3432     120  2020-04-30
123  San Diego County       3432     120  2020-04-29
124  San Diego County       3141     113  2020-04-28
125  San Diego County       3043     111  2020-04-27
126  San Diego County       2943     111  2020-04-26
127  San Diego County       2943     111  2020-04-25
128  San Diego County       2826     102  2020-04-24
129  San Diego County       2643     100  2020-04-23
130  San Diego County       2491      96  2020-04-22
131  San Diego County       2325      72  2020-04-21
132  San Diego County       2268      71  2020-04-20
133  San Diego County       2213      71  2020-04-19
134  San Diego County       2158      70  2020-04-18
135  San Diego County       2087      63  2020-04-17
136  San Diego County       2012      60  2020-04-16
137  San Diego County       1930      53  2020-04-15
138  San Diego County       1847      47  2020-04-14
139  San Diego County       1804      45  2020-04-13
140  San Diego County       1761      45  2020-04-12
141  San Diego County       1693      44  2020-04-11
142  San Diego County       1628      40  2020-04-10
143  San Diego County       1530      36  2020-04-09
144  San Diego County       1454      31  2020-04-08
145  San Diego County       1404      19  2020-04-07
146  San Diego County       1326      19  2020-04-06
147  San Diego County       1209      18  2020-04-05
148  San Diego County       1112      17  2020-04-04
149  San Diego County        966      16  2020-04-03
150  San Diego County        849      15  2020-04-02
151  San Diego County        733       9  2020-04-01
152  San Diego County        603       7  2020-03-31
153  San Diego County        515       7  2020-03-30
154  San Diego County        484       7  2020-03-29
155  San Diego County        413       6  2020-03-28
156  San Diego County        341       3  2020-03-27
157  San Diego County        293       3  2020-03-26
158  San Diego County        238       2  2020-03-25
159  San Diego County        226       1  2020-03-24
160  San Diego County        201       1  2020-03-23
161  San Diego County        155       0  2020-03-22
162  San Diego County        127       0  2020-03-21
163  San Diego County        127       0  2020-03-20
164  San Diego County         80       0  2020-03-19
165  San Diego County         60       0  2020-03-18
166  San Diego County         55       0  2020-03-17
167  San Diego County         55       0  2020-03-16
168  San Diego County         16       0  2020-03-15
169  San Diego County         10       0  2020-03-14
170  San Diego County          8       0  2020-03-13
171  San Diego County          5       0  2020-03-12
172  San Diego County          3       0  2020-03-11
173  San Diego County          3       0  2020-03-10
174  San Diego County          3       0  2020-03-09
175  San Diego County          3       0  2020-03-08
176  San Diego County          3       0  2020-03-07
177  San Diego County          3       0  2020-03-06
178  San Diego County          3       0  2020-03-05
179  San Diego County          2       0  2020-03-04
180  San Diego County          2       0  2020-03-03
181  San Diego County          2       0  2020-03-02
182  San Diego County          2       0  2020-03-01
183  San Diego County          2       0  2020-02-29
184  San Diego County          2       0  2020-02-28
185  San Diego County          2       0  2020-02-27
186  San Diego County          2       0  2020-02-26
187  San Diego County          2       0  2020-02-25
188  San Diego County          2       0  2020-02-24
189  San Diego County          2       0  2020-02-23
190  San Diego County          2       0  2020-02-22
191  San Diego County          2       0  2020-02-21
192  San Diego County          2       0  2020-02-20
193  San Diego County          2       0  2020-02-19
194  San Diego County          2       0  2020-02-18
195  San Diego County          2       0  2020-02-17
196  San Diego County          2       0  2020-02-16
197  San Diego County          2       0  2020-02-15
198  San Diego County          2       0  2020-02-14
199  San Diego County          2       0  2020-02-13
200  San Diego County          1       0  2020-02-12
201  San Diego County          1       0  2020-02-11

### COVID-19 Cases in San Diego Country by Zip code
The latest data may show up with a delay. If no output is show, adjust the date to a day earlier using this format: `date('2020-06-21')`.

In [9]:
query = """
MATCH (c:Cases{date: date($day), source: 'SDHHSA'})-[:REPORTED_IN]->(p:PostalCode)
RETURN p.name as zip, p.placeName, p.location, c.cases as confirmed, c.date as date
ORDER by zip
"""
graph.run(query, day=yesterday).to_data_frame()

       zip         p.placeName            p.location  confirmed        date
0    91901              Alpine  (-116.7543, 32.8282)         95  2020-08-29
1    91902              Bonita  (-117.0221, 32.6671)        220  2020-08-29
2    91905           Boulevard    (-116.32, 32.6719)          7  2020-08-29
3    91906               Campo  (-116.4905, 32.6605)         19  2020-08-29
4    91910         Chula Vista  (-117.0676, 32.6371)       1595  2020-08-29
5    91911         Chula Vista  (-117.0565, 32.6084)       1914  2020-08-29
6    91913         Chula Vista  (-116.9852, 32.6513)        686  2020-08-29
7    91914         Chula Vista  (-116.9652, 32.6587)        233  2020-08-29
8    91915         Chula Vista  (-116.9408, 32.6315)        409  2020-08-29
9    91916            Descanso   (-116.6027, 32.873)         10  2020-08-29
10   91917             Dulzura  (-116.7285, 32.6152)         45  2020-08-29
11   91932      Imperial Beach  (-117.1148, 32.5783)        483  2020-08-29
12   91934             Jacumba  (-116.1952, 32.6249)          2  2020-08-29
13   91935               Jamul  (-116.8323, 32.7163)         74  2020-08-29
14   91941             La Mesa  (-117.0115, 32.7604)        314  2020-08-29
15   91942             La Mesa  (-117.0189, 32.7835)        384  2020-08-29
16   91945         Lemon Grove  (-117.0326, 32.7332)        406  2020-08-29
17   91950       National City  (-117.0897, 32.6749)       1446  2020-08-29
18   91962         Pine Valley   (-116.5127, 32.835)          5  2020-08-29
19   91963             Potrero  (-116.6037, 32.6205)         34  2020-08-29
20   91977       Spring Valley   (-116.9976, 32.724)       1129  2020-08-29
21   91978       Spring Valley  (-116.9596, 32.7329)        118  2020-08-29
22   91980              Tecate  (-116.6192, 32.5889)         22  2020-08-29
23   92003             Bonsall   (-117.1897, 33.294)         41  2020-08-29
24   92004     Borrego Springs  (-116.3514, 33.2386)         17  2020-08-29
25   92007  Cardiff By The Sea   (-117.2745, 33.023)         46  2020-08-29
26   92008            Carlsbad   (-117.325, 33.1602)        175  2020-08-29
27   92009            Carlsbad  (-117.2619, 33.0954)        219  2020-08-29
28   92010            Carlsbad  (-117.3009, 33.1639)         83  2020-08-29
29   92011            Carlsbad  (-117.2943, 33.1072)        116  2020-08-29
30   92014             Del Mar   (-117.249, 32.9665)         67  2020-08-29
31   92019            El Cajon  (-116.9191, 32.7777)        571  2020-08-29
32   92020            El Cajon  (-116.9665, 32.7928)       1054  2020-08-29
33   92021            El Cajon  (-116.9223, 32.8178)        989  2020-08-29
34   92024           Encinitas  (-117.2689, 33.0535)        295  2020-08-29
35   92025           Escondido    (-117.07, 33.1101)        599  2020-08-29
36   92026           Escondido  (-117.0978, 33.1605)        546  2020-08-29
37   92027           Escondido   (-117.052, 33.1388)        696  2020-08-29
38   92028           Fallbrook    (-117.229, 33.369)        431  2020-08-29
39   92029           Escondido  (-117.1128, 33.0895)        108  2020-08-29
40   92036              Julian  (-116.5658, 33.0534)         10  2020-08-29
41   92037            La Jolla  (-117.2521, 32.8455)        262  2020-08-29
42   92040            Lakeside  (-116.9201, 32.8562)        342  2020-08-29
43   92054           Oceanside  (-117.3573, 33.2072)        339  2020-08-29
44   92055      Camp Pendleton  (-117.3768, 33.2433)         85  2020-08-29
45   92056           Oceanside  (-117.2831, 33.1968)        397  2020-08-29
46   92057           Oceanside  (-117.3025, 33.2407)        440  2020-08-29
47   92058           Oceanside  (-117.3795, 33.1959)        258  2020-08-29
48   92059                Pala  (-117.0717, 33.3777)         71  2020-08-29
49   92060    Palomar Mountain  (-116.8786, 33.3228)          2  2020-08-29
50   92061        Pauma Valley  (-116.9596, 33.3063)         15  2020-08-29
51   92064               Poway  (-117.0402, 32.9756)        234  2020-08-29
52   92065              Ramona  (-116.8535, 33.0293)        267  2020-08-29
53   92066            Ranchita    (-116.5167, 33.21)          3  2020-08-29
54   92067     Rancho Santa Fe   (-117.2157, 33.005)         52  2020-08-29
55   92069          San Marcos  (-117.1697, 33.1444)        517  2020-08-29
56   92070        Santa Ysabel  (-116.6963, 33.1476)          3  2020-08-29
57   92071              Santee  (-116.9862, 32.8486)        384  2020-08-29
58   92075        Solana Beach  (-117.2598, 32.9937)         47  2020-08-29
59   92078          San Marcos   (-117.185, 33.1193)        362  2020-08-29
60   92081               Vista  (-117.2403, 33.1644)        162  2020-08-29
61   92082       Valley Center   (-117.0122, 33.249)        131  2020-08-29
62   92083               Vista  (-117.2482, 33.1978)        484  2020-08-29
63   92084               Vista  (-117.2243, 33.2131)        487  2020-08-29
64   92086      Warner Springs  (-116.6527, 33.3096)         18  2020-08-29
65   92091     Rancho Santa Fe  (-117.0462, 32.9623)          7  2020-08-29
66   92093            La Jolla  (-117.2742, 32.8473)          6  2020-08-29
67   92101           San Diego  (-117.1593, 32.7185)        636  2020-08-29
68   92102           San Diego  (-117.1219, 32.7139)        867  2020-08-29
69   92103           San Diego  (-117.1636, 32.7466)        319  2020-08-29
70   92104           San Diego  (-117.1272, 32.7454)        477  2020-08-29
71   92105           San Diego  (-117.0947, 32.7423)       1250  2020-08-29
72   92106           San Diego  (-117.2268, 32.7272)        108  2020-08-29
73   92107           San Diego  (-117.2433, 32.7425)        166  2020-08-29
74   92108           San Diego  (-117.1335, 32.7783)        276  2020-08-29
75   92109           San Diego  (-117.2405, 32.7969)        531  2020-08-29
76   92110           San Diego  (-117.2028, 32.7635)        231  2020-08-29
77   92111           San Diego  (-117.1708, 32.7972)        400  2020-08-29
78   92113           San Diego   (-117.1153, 32.697)       1456  2020-08-29
79   92114           San Diego  (-117.0524, 32.7059)       1173  2020-08-29
80   92115           San Diego  (-117.0721, 32.7607)        856  2020-08-29
81   92116           San Diego  (-117.1242, 32.7624)        250  2020-08-29
82   92117           San Diego  (-117.1965, 32.8239)        378  2020-08-29
83   92118            Coronado  (-117.1698, 32.6807)        124  2020-08-29
84   92119           San Diego  (-117.0261, 32.8036)        127  2020-08-29
85   92120           San Diego  (-117.0707, 32.7958)        197  2020-08-29
86   92121           San Diego  (-117.2035, 32.8919)         20  2020-08-29
87   92122           San Diego  (-117.2115, 32.8577)        159  2020-08-29
88   92123           San Diego  (-117.1392, 32.7973)        238  2020-08-29
89   92124           San Diego  (-117.0986, 32.8201)        155  2020-08-29
90   92126           San Diego  (-117.1402, 32.9161)        460  2020-08-29
91   92127           San Diego  (-117.0856, 33.0279)        201  2020-08-29
92   92128           San Diego   (-117.069, 33.0067)        228  2020-08-29
93   92129           San Diego  (-117.1213, 32.9652)        228  2020-08-29
94   92130           San Diego  (-117.2252, 32.9555)        264  2020-08-29
95   92131           San Diego  (-117.0898, 32.9123)        147  2020-08-29
96   92134           San Diego  (-117.1466, 32.7242)         12  2020-08-29
97   92135           San Diego  (-117.1573, 32.7153)         38  2020-08-29
98   92136           San Diego  (-117.1219, 32.6834)         88  2020-08-29
99   92139           San Diego  (-117.0474, 32.6806)        645  2020-08-29
100  92140           San Diego  (-117.2004, 32.7434)         89  2020-08-29
101  92145           San Diego  (-117.1005, 32.8891)          8  2020-08-29
102  92154           San Diego  (-117.0707, 32.5753)       2319  2020-08-29
103  92173          San Ysidro   (-117.043, 32.5626)       1277  2020-08-29
104  92536             Aguanga  (-116.7997, 33.4473)          1  2020-08-29

### COVID 19 Cases Time Series for Carlsbad, California
Cases are aggregated from the zip-level data (note, some zip code areas may cross city boundaries)

In [10]:
query = """
MATCH (c:Cases{source: 'SDHHSA'})-[:REPORTED_IN]->(p:PostalCode{placeName:'Carlsbad'})-[:IN*]->(a:Admin1{name: 'California'})
RETURN c.date as date, sum(c.cases) as confirmed
ORDER by date DESC
"""
graph.run(query).to_data_frame()

           date  confirmed
0    2020-08-29        593
1    2020-08-28        591
2    2020-08-27        585
3    2020-08-26        584
4    2020-08-25        575
5    2020-08-24        574
6    2020-08-23        573
7    2020-08-22        568
8    2020-08-21        561
9    2020-08-20        559
10   2020-08-19        557
11   2020-08-18        555
12   2020-08-17        555
13   2020-08-16        552
14   2020-08-15        551
15   2020-08-14        543
16   2020-08-13        537
17   2020-08-12        533
18   2020-08-11        530
19   2020-08-10        524
20   2020-08-09        524
21   2020-08-08        521
22   2020-08-07        518
23   2020-08-06        516
24   2020-08-05        500
25   2020-08-04        499
26   2020-08-03        496
27   2020-08-02        489
28   2020-08-01        485
29   2020-07-31        485
30   2020-07-30        478
31   2020-07-29        472
32   2020-07-28        466
33   2020-07-27        452
34   2020-07-26        444
35   2020-07-25        439
36   2020-07-24        432
37   2020-07-23        424
38   2020-07-22        420
39   2020-07-21        412
40   2020-07-20        402
41   2020-07-19        395
42   2020-07-18        385
43   2020-07-17        380
44   2020-07-16        365
45   2020-07-15        345
46   2020-07-14        334
47   2020-07-13        325
48   2020-07-12        318
49   2020-07-11        311
50   2020-07-10        295
51   2020-07-09        285
52   2020-07-08        273
53   2020-07-07        267
54   2020-07-06        255
55   2020-07-05        246
56   2020-07-04        234
57   2020-07-03        217
58   2020-07-02        198
59   2020-07-01        191
60   2020-06-30        182
61   2020-06-29        167
62   2020-06-28        160
63   2020-06-27        155
64   2020-06-26        149
65   2020-06-25        139
66   2020-06-24        136
67   2020-06-23        127
68   2020-06-22        122
69   2020-06-21        115
70   2020-06-20        111
71   2020-06-19        104
72   2020-06-18        103
73   2020-06-17         98
74   2020-06-16         96
75   2020-06-15         93
76   2020-06-14         92
77   2020-06-13         90
78   2020-06-12         89
79   2020-06-11         88
80   2020-06-10         86
81   2020-06-09         85
82   2020-06-08         86
83   2020-06-07         85
84   2020-06-06         84
85   2020-06-05         84
86   2020-06-04         82
87   2020-06-03         80
88   2020-06-02         77
89   2020-06-01         77
90   2020-05-31         77
91   2020-05-30         76
92   2020-05-29         76
93   2020-05-28         76
94   2020-05-27         75
95   2020-05-26         75
96   2020-05-25         73
97   2020-05-24         73
98   2020-05-23         73
99   2020-05-22         73
100  2020-05-21         73
101  2020-05-20         72
102  2020-05-19         71
103  2020-05-18         71
104  2020-05-17         71
105  2020-05-16         71
106  2020-05-15         70
107  2020-05-14         69
108  2020-05-13         69
109  2020-05-12         66
110  2020-05-11         63
111  2020-05-10         63
112  2020-05-09         61
113  2020-05-08         58
114  2020-05-07         58
115  2020-05-06         58
116  2020-05-05         57
117  2020-05-04         57
118  2020-05-03         56
119  2020-05-02         56
120  2020-05-01         56
121  2020-04-30         56
122  2020-04-29         54
123  2020-04-28         52
124  2020-04-27         51
125  2020-04-26         50
126  2020-04-25         50
127  2020-04-24         50
128  2020-04-23         50
129  2020-04-22         50
130  2020-04-21         50
131  2020-04-20         50
132  2020-04-19         50
133  2020-04-18         50
134  2020-04-17         50
135  2020-04-16         50
136  2020-04-15         50
137  2020-04-14         50
138  2020-04-13         49
139  2020-04-12         48
140  2020-04-11         48
141  2020-04-10         48
142  2020-04-09         48
143  2020-04-08         43
144  2020-04-07         43
145  2020-04-06         42
146  2020-04-05         42
147  2020-04-04         42
148  2020-04-03         41
149  2020-04-02         39
150  2020-04-01         37
151  2020-03-31         32
152  2020-03-30         31

### COVID-19 cases aggregated by US Regions
Here we aggregate US county-level data over 2 hops:

`Admin2 -> USDivision -> USRegion`

using the variable-length relationship [:IN*].

In [11]:
query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(:Admin2)-[:IN*]->(u:USRegion)
RETURN sum(c.cases) AS count, u.name AS USRegion
ORDER by count DESC
"""
graph.run(query, day=yesterday).to_data_frame()

     count          USRegion
0  2696928      South Region
1  1249632       West Region
2   965376  Northeast Region
3   936911    Midwest Region

### COVID-19 cases aggregated by UN Region
Here we aggregate country-level data over up to 3 hops:

`country -> UNSubRegion -> UNIntermediateRegion -> UNRegion`

using the variable-length relationship `[:IN*`].

In [12]:
query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(:Country)-[:IN*]->(u:UNRegion)
RETURN sum(c.cases) AS count, u.name AS UNRegion
ORDER by count DESC
"""
df = graph.run(query, day=yesterday).to_data_frame()
df

      count  UNRegion
0  13156406  Americas
1   6808125      Asia
2   3546247    Europe
3   1241841    Africa
4      2715   Oceania

In [13]:
print("Total number of confirmed cases:", df['count'].sum())

Total number of confirmed cases: 24755334