# Example queries for Case Counts on COVID-19 Knowledge Graph
[Work in progress]

This notebook demonstrates how to run Cypher queries to retrieve and aggregate COVID-19 case counts.

COVID-19 case numbers are provided by:

Country and US County level data: [JHU](https://github.com/covid-19-net/covid-19-community/blob/master/reference_data/DataProvider.csv#L6)

San Diego data by zip code: [SDHHSA](https://github.com/covid-19-net/covid-19-community/blob/master/reference_data/DataProvider.csv#L7)

In [1]:
import datetime
import pandas as pd
from py2neo import Graph

In [2]:
pd.options.display.max_rows = None  # display all rows
pd.options.display.max_columns = None  # display all columsns

#### Connect to COVID-19-Net Knowledge Graph

In [3]:
graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")

#### Get lastest update day for JHU data

In [4]:
query = """
MATCH (:Admin2)<-[:REPORTED_IN]-(c:Cases{source: 'JHU'}) 
RETURN max(c.date)  // returns a neotime.Date object
"""
date = graph.evaluate(query).to_native() # convert to datetime.date object

## COVID Case Data

### Case counts by Country (using Johns Hopkins COVID-19 data)

In [5]:
query = """
MATCH (c:Cases{date: date($date), source: 'JHU'})-[:REPORTED_IN]->(n:Country)
RETURN n.name, c.cases, c.deaths, c.date as date
ORDER by n.name
"""
graph.run(query, date=date).to_data_frame()

                               n.name   c.cases  c.deaths        date
0                         Afghanistan     54483      2370  2021-01-22
1                             Albania     70655      1303  2021-01-22
2                             Algeria    105124      2856  2021-01-22
3                             Andorra      9416        93  2021-01-22
4                              Angola     19269       452  2021-01-22
5                            Anguilla        15         0  2021-01-22
6                 Antigua and Barbuda       195         6  2021-01-22
7                           Argentina   1853830     46575  2021-01-22
8                             Armenia    165711      3030  2021-01-22
9                               Aruba      6656        56  2021-01-22
10                            Austria    401886      7330  2021-01-22
11                         Azerbaijan    228526      3064  2021-01-22
12                            Bahamas      8101       175  2021-01-22
13                            Bahrain     99210       366  2021-01-22
14                         Bangladesh    530890      7981  2021-01-22
15                           Barbados      1156         9  2021-01-22
16                            Belarus    234111      1628  2021-01-22
17                            Belgium    689271     20675  2021-01-22
18                             Belize     11700       290  2021-01-22
19                              Benin      3643        48  2021-01-22
20                            Bermuda       684        12  2021-01-22
21                             Bhutan       851         1  2021-01-22
22                            Bolivia    198257      9871  2021-01-22
23             Bosnia and Herzegovina    119420      4555  2021-01-22
24                           Botswana     19654       105  2021-01-22
25                             Brazil   8753920    215243  2021-01-22
26             British Virgin Islands       114         1  2021-01-22
27                             Brunei       175         3  2021-01-22
28                           Bulgaria    214430      8799  2021-01-22
29                       Burkina Faso      9857       107  2021-01-22
30                            Burundi      1380         2  2021-01-22
31                         Cabo Verde     13381       122  2021-01-22
32                           Cambodia       456         0  2021-01-22
33                           Cameroon     28010       455  2021-01-22
34                             Canada        13         0  2021-01-22
35                     Cayman Islands       382         2  2021-01-22
36           Central African Republic      4974        63  2021-01-22
37                               Chad      3104       115  2021-01-22
38                              Chile    690066     17786  2021-01-22
39                           Colombia   1987418     50586  2021-01-22
40                            Comoros      2160        63  2021-01-22
41                         Costa Rica    189308      2518  2021-01-22
42                            Croatia    227969      4770  2021-01-22
43                               Cuba     20060       188  2021-01-22
44                            Curacao      4543        20  2021-01-22
45                             Cyprus     29758       179  2021-01-22
46                            Czechia    924847     15130  2021-01-22
47   Democratic Republic of the Congo     21597       647  2021-01-22
48                            Denmark    193038      1941  2021-01-22
49                           Djibouti      5917        61  2021-01-22
50                           Dominica       113         0  2021-01-22
51                 Dominican Republic    201145      2496  2021-01-22
52                            Ecuador    237158     14562  2021-01-22
53                              Egypt    160463      8853  2021-01-22
54                        El Salvador     52672      1540  2021-01-22
55                  Equatorial Guinea      5401        86  2021-01-22
56                            Eritrea      1940         6  2021-01-22
57                            Estonia     39701       358  2021-01-22
58                           Eswatini     14219       458  2021-01-22
59                           Ethiopia    132881      2060  2021-01-22
60                   Falkland Islands        35         0  2021-01-22
61                      Faroe Islands       652         1  2021-01-22
62                               Fiji        55         2  2021-01-22
63                            Finland     41915       644  2021-01-22
64                             France         4         0  2021-01-22
65                             France   3002910     72268  2021-01-22
66                      French Guiana     15431        76  2021-01-22
67                   French Polynesia     17852       128  2021-01-22
68                              Gabon     10278        67  2021-01-22
69                             Gambia      3958       128  2021-01-22
70                            Georgia    251974      3022  2021-01-22
71                            Germany   2125261     51713  2021-01-22
72                              Ghana     59480       361  2021-01-22
73                          Gibraltar      3905        59  2021-01-22
74                             Greece    151041      5598  2021-01-22
75                          Greenland        30         0  2021-01-22
76                            Grenada       139         1  2021-01-22
77                         Guadeloupe      8948       156  2021-01-22
78                          Guatemala    152956      5420  2021-01-22
79                           Guernsey      3414        78  2021-01-22
80                             Guinea     14262        81  2021-01-22
81                      Guinea-Bissau      2510        45  2021-01-22
82                             Guyana      7143       170  2021-01-22
83                              Haiti     11035       243  2021-01-22
84                           Honduras    139182      3439  2021-01-22
85                          Hong Kong      9928       168  2021-01-22
86                            Hungary    356973     11811  2021-01-22
87                            Iceland      5981        29  2021-01-22
88                              India  10639684    153184  2021-01-22
89                          Indonesia    965283     27453  2021-01-22
90                               Iran   1360852     57225  2021-01-22
91                               Iraq    612092     12984  2021-01-22
92                            Ireland    184279      2870  2021-01-22
93                        Isle of Man       432        25  2021-01-22
94                             Israel    589028      4266  2021-01-22
95                              Italy   2441854     84674  2021-01-22
96                        Ivory Coast     26315       143  2021-01-22
97                            Jamaica     14658       332  2021-01-22
98                              Japan    357174      4980  2021-01-22
99                             Jordan    318911      4207  2021-01-22
100                        Kazakhstan    222701      2953  2021-01-22
101                             Kenya     99769      1740  2021-01-22
102                            Kosovo     57317      1447  2021-01-22
103                            Kuwait    160367       952  2021-01-22
104                        Kyrgyzstan     83796      1398  2021-01-22
105                              Laos        41         0  2021-01-22
106                            Latvia     59586      1076  2021-01-22
107                           Lebanon    272461      2208  2021-01-22
108                           Lesotho      7555       113  2021-01-22
109                           Liberia      1912        84  2021-01-22
110                             Libya    112540      1737  2021-01-22
111                     Liechtenstein      2432        52  2021-01-22
112                         Lithuania    174846      2591  2021-01-22
113                        Luxembourg     49438       562  2021-01-22
114                        Madagascar     18301       273  2021-01-22
115                            Malawi     17365       445  2021-01-22
116                          Malaysia    176180       660  2021-01-22
117                          Maldives     14830        50  2021-01-22
118                              Mali      7937       321  2021-01-22
119                             Malta     16423       248  2021-01-22
120                  Marshall Islands         4         0  2021-01-22
121                        Martinique      6302        44  2021-01-22
122                        Mauritania     16322       413  2021-01-22
123                         Mauritius       556        10  2021-01-22
124                           Mayotte      7158        58  2021-01-22
125                            Mexico   1732290    147614  2021-01-22
126                        Micronesia         1         0  2021-01-22
127                           Moldova    155302      3332  2021-01-22
128                            Monaco      1311         9  2021-01-22
129                          Mongolia      1611         2  2021-01-22
130                        Montenegro     57482       765  2021-01-22
131                        Montserrat        13         1  2021-01-22
132                           Morocco    464844      8105  2021-01-22
133                        Mozambique     30848       290  2021-01-22
134                           Myanmar    136591      3031  2021-01-22
135                           Namibia     31848       311  2021-01-22
136                             Nepal    268948      1986  2021-01-22
137                       Netherlands    938628     13422  2021-01-22
138                     New Caledonia        44         0  2021-01-22
139                       New Zealand      2276        25  2021-01-22
140                         Nicaragua      6204       168  2021-01-22
141                             Niger      4308       150  2021-01-22
142                           Nigeria    118138      1490  2021-01-22
143                   North Macedonia     90124      2768  2021-01-22
144                            Norway     60565       544  2021-01-22
145                              Oman    132486      1517  2021-01-22
146                          Pakistan    530818     11247  2021-01-22
147             Palestinian Territory    154557      1769  2021-01-22
148                            Panama    307793      4980  2021-01-22
149                  Papua New Guinea       835         9  2021-01-22
150                          Paraguay    126370      2585  2021-01-22
151                              Peru   1082907     39274  2021-01-22
152                       Philippines    509887     10136  2021-01-22
153                            Poland   1464448     34908  2021-01-22
154                          Portugal    609136      9920  2021-01-22
155                             Qatar    148521       248  2021-01-22
156             Republic of the Congo      7794       117  2021-01-22
157                           Reunion      9584        45  2021-01-22
158                           Romania    706475     17628  2021-01-22
159                            Russia   3637862     67376  2021-01-22
160                            Rwanda     12443       165  2021-01-22
161                  Saint Barthelemy       300         1  2021-01-22
162             Saint Kitts and Nevis        35         0  2021-01-22
163                       Saint Lucia       755        10  2021-01-22
164                      Saint Martin      1146        12  2021-01-22
165         Saint Pierre and Miquelon        16         0  2021-01-22
166  Saint Vincent and the Grenadines       690         2  2021-01-22
167                             Samoa         2         0  2021-01-22
168                        San Marino      2861        65  2021-01-22
169             Sao Tome and Principe      1182        17  2021-01-22
170                      Saudi Arabia    365988      6346  2021-01-22
171                           Senegal     24209       561  2021-01-22
172                            Serbia    380802      3849  2021-01-22
173                        Seychelles       972         3  2021-01-22
174                      Sierra Leone      3093        77  2021-01-22
175                         Singapore     59250        29  2021-01-22
176                      Sint Maarten      1724        27  2021-01-22
177                          Slovakia    233027      3894  2021-01-22
178                          Slovenia    155752      3309  2021-01-22
179                   Solomon Islands        17         0  2021-01-22
180                           Somalia      4744       130  2021-01-22
181                      South Africa   1392568     40076  2021-01-22
182                       South Korea     74692      1337  2021-01-22
183                       South Sudan      3788        64  2021-01-22
184                             Spain   2499560     55441  2021-01-22
185                         Sri Lanka     56863       278  2021-01-22
186                             Sudan     26279      1603  2021-01-22
187                          Suriname      7945       148  2021-01-22
188                            Sweden    547166     11005  2021-01-22
189                       Switzerland    509279      9034  2021-01-22
190                             Syria     13479       873  2021-01-22
191                            Taiwan       881         7  2021-01-22
192                        Tajikistan     13308        90  2021-01-22
193                          Tanzania       509        21  2021-01-22
194                          Thailand     13104        71  2021-01-22
195                       Timor Leste        53         0  2021-01-22
196                              Togo      4545        74  2021-01-22
197               Trinidad and Tobago      7456       133  2021-01-22
198                           Tunisia    193273      6092  2021-01-22
199                            Turkey   2418472     24789  2021-01-22
200          Turks and Caicos Islands      1193         7  2021-01-22
201                            Uganda     38935       317  2021-01-22
202                           Ukraine   1222459     22698  2021-01-22
203              United Arab Emirates    270810       776  2021-01-22
204                    United Kingdom   3583907     95981  2021-01-22
205                     United States  24818779    414004  2021-01-22
206                           Uruguay     36170       364  2021-01-22
207                        Uzbekistan     78272       620  2021-01-22
208                           Vanuatu         1         0  2021-01-22
209                           Vatican        27         0  2021-01-22
210                         Venezuela    122795      1136  2021-01-22
211                           Vietnam      1548        35  2021-01-22
212                             Yemen      2118       614  2021-01-22
213                            Zambia     43333       610  2021-01-22
214                          Zimbabwe     30523       962  2021-01-22

### Case counts by US States aggregated from US Counties
Note, some counties in the Johns Hopkins dataset cannot be mapped to US counties. They are listed in as "None"

In [6]:
query = """
MATCH (c:Cases{date: $date, source: 'JHU'})-[:REPORTED_IN]->(a:Admin2)-[:IN]->(a1:Admin1)
RETURN a1.name as state, a1.code, a1.location, sum(c.deaths) as deaths, sum(c.cases) as confirmed, c.date as date
ORDER BY a1.code
"""
graph.run(query, date=date).to_data_frame()

,state,a1.code,a1.location,deaths,confirmed,date
0,Alaska,AK,"(-150.00028, 64.00028)",254,52669,2021-01-22
1,Alabama,AL,"(-86.75026, 32.75041)",6486,436087,2021-01-22
2,Arkansas,AR,"(-92.50044, 34.75037)",4549,278195,2021-01-22
3,Arizona,AZ,"(-111.50098, 34.5003)",12001,708040,2021-01-22
4,California,CA,"(-119.75126, 37.25022)",36259,3121386,2021-01-22
5,Colorado,CO,"(-105.50083, 39.00027)",5462,382973,2021-01-22
6,Connecticut,CT,"(-72.66648, 41.66704)",6814,237028,2021-01-22
7,District of Columbia,DC,"(-77.00025, 38.91706)",867,34905,2021-01-22
8,Delaware,DE,"(-75.49992, 39.00039)",1027,73061,2021-01-22
9,Florida,FL,"(-82.5001, 28.75054)",25011,1624312,2021-01-22
10,Georgia,GA,"(-83.50018, 32.75042)",12639,821097,2021-01-22
11,Hawaii,HI,"(-156.38612, 20.78785)",329,24823,2021-01-22
12,Iowa,IA,"(-93.50049, 42.00027)",4478,310690,2021-01-22
13,Idaho,ID,"(-114.25118, 44.5002)",1667,158798,2021-01-22
14,Illinois,IL,"(-89.25037, 40.00032)",20534,1093220,2021-01-22
15,Indiana,IN,"(-86.25027, 40.00032)",9267,605426,2021-01-22
16,Kansas,KS,"(-98.50063, 38.50029)",3587,268908,2021-01-22
17,Kentucky,KY,"(-84.87762, 38.20042)",3337,340778,2021-01-22
18,Louisiana,LA,"(-92.0004, 31.00047)",8483,379843,2021-01-22
19,Massachusetts,MA,"(-71.10832, 42.36565)",13977,464664,2021-01-22
20,Maryland,MD,"(-76.74997, 39.00039)",6745,336915,2021-01-22
21,Maine,ME,"(-69.24977, 45.50032)",540,36255,2021-01-22
22,Michigan,MI,"(-85.50033, 44.25029)",14797,569318,2021-01-22
23,Minnesota,MN,"(-94.25055, 46.25024)",6032,451831,2021-01-22
24,Missouri,MO,"(-92.50046, 38.25031)",6330,423556,2021-01-22
25,Mississippi,MS,"(-89.75036, 32.75041)",5713,261167,2021-01-22
26,Montana,MT,"(-109.75102, 47.00025)",1104,91049,2021-01-22
27,North Carolina,NC,"(-80.00032, 35.50069)",8464,705158,2021-01-22
28,North Dakota,ND,"(-100.00068, 47.50027)",1403,96565,2021-01-22
29,Nebraska,NE,"(-99.75067, 41.50028)",1875,184898,2021-01-22
30,New Hampshire,NH,"(-71.4998, 43.66702)",970,59904,2021-01-22
31,New Jersey,NJ,"(-74.49987, 40.16706)",20875,649171,2021-01-22
32,New Mexico,NM,"(-106.00085, 34.50034)",3077,164145,2021-01-22
33,Nevada,NV,"(-116.75119, 39.25021)",3958,268212,2021-01-22
34,New York,NY,"(-75.4999, 43.00035)",41689,1309341,2021-01-22
35,Ohio,OH,"(-83.00018, 40.25034)",10599,853982,2021-01-22
36,Oklahoma,OK,"(-97.50328, 35.49209)",3187,365848,2021-01-22
37,Oregon,OR,"(-120.50139, 44.00013)",1865,136839,2021-01-22
38,Pennsylvania,PA,"(-77.7, 40.8)",20269,798438,2021-01-22
39,Rhode Island,RI,"(-71.49978, 41.75038)",2010,97202,2021-01-22
40,South Carolina,SC,"(-81.00009, 34.00043)",6404,409188,2021-01-22
41,South Dakota,SD,"(-100.25069, 44.50026)",1684,106716,2021-01-22
42,Tennessee,TN,"(-86.25027, 35.75035)",8561,662108,2021-01-22
43,Texas,TX,"(-99.25061, 31.25044)",34381,2227789,2021-01-22
44,Utah,UT,"(-111.75103, 39.25024)",1103,252997,2021-01-22
45,Virginia,VA,"(-77.44675, 37.54812)",6002,463751,2021-01-22
46,Vermont,VT,"(-72.74983, 44.00034)",169,10751,2021-01-22
47,Washington,WA,"(-120.50147, 47.50012)",4110,296815,2021-01-22
48,Wisconsin,WI,"(-90.00041, 44.50024)",6135,577991,2021-01-22
49,West Virginia,WV,"(-80.50009, 38.50038)",1856,113615,2021-01-22
50,Wyoming,WY,"(-107.5009, 43.00024)",571,50583,2021-01-22

### Current cases in San Diego County

In [7]:
admin2 = 'San Diego County'

query = """
MATCH (c:Cases{date: date($date), source: 'JHU'})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cases as confirmed, c.deaths as deaths, c.date as date
"""
graph.run(query, admin2=admin2, date=date).to_data_frame()

               name  confirmed  deaths        date
0  San Diego County     222578    2301  2021-01-22

### COVID-19 Cases Time Series in San Diego County

In [8]:
query = """
MATCH (c:Cases{source: 'JHU'})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cases as confirmed, c.deaths as deaths, c.date as date
ORDER BY c.date DESC
"""
graph.run(query, admin2=admin2).to_data_frame()

                 name  confirmed  deaths        date
0    San Diego County     222578    2301  2021-01-22
1    San Diego County     219731    2222  2021-01-21
2    San Diego County     218555    2174  2021-01-20
3    San Diego County     216835    2109  2021-01-19
4    San Diego County     214337    2103  2021-01-18
5    San Diego County     211787    2103  2021-01-17
6    San Diego County     209897    2065  2021-01-16
7    San Diego County     206870    2037  2021-01-15
8    San Diego County     204175    2005  2021-01-14
9    San Diego County     201580    1952  2021-01-13
10   San Diego County     198319    1898  2021-01-12
11   San Diego County     194795    1857  2021-01-11
12   San Diego County     191888    1857  2021-01-10
13   San Diego County     188600    1824  2021-01-09
14   San Diego County     185062    1771  2021-01-08
15   San Diego County     180512    1738  2021-01-07
16   San Diego County     176662    1691  2021-01-06
17   San Diego County     172847    1654  2021-01-05
18   San Diego County     171033    1598  2021-01-04
19   San Diego County     168020    1592  2021-01-03
20   San Diego County     164500    1592  2021-01-02
21   San Diego County     160073    1592  2021-01-01
22   San Diego County     155595    1534  2020-12-31
23   San Diego County     152512    1472  2020-12-30
24   San Diego County     150064    1435  2020-12-29
25   San Diego County     147530    1404  2020-12-28
26   San Diego County     145779    1402  2020-12-27
27   San Diego County     142647    1402  2020-12-26
28   San Diego County     139961    1402  2020-12-25
29   San Diego County     136955    1382  2020-12-24
30   San Diego County     134696    1350  2020-12-23
31   San Diego County     132098    1311  2020-12-22
32   San Diego County     129717    1283  2020-12-21
33   San Diego County     126465    1280  2020-12-20
34   San Diego County     122972    1280  2020-12-19
35   San Diego County     120463    1253  2020-12-18
36   San Diego County     116852    1239  2020-12-17
37   San Diego County     114248    1217  2020-12-16
38   San Diego County     111441    1194  2020-12-15
39   San Diego County     109578    1162  2020-12-14
40   San Diego County     107372    1162  2020-12-13
41   San Diego County     104956    1151  2020-12-12
42   San Diego County     102466    1137  2020-12-11
43   San Diego County      99599    1114  2020-12-10
44   San Diego County      97549    1103  2020-12-09
45   San Diego County      95445    1088  2020-12-08
46   San Diego County      94169    1062  2020-12-07
47   San Diego County      92171    1062  2020-12-06
48   San Diego County      90468    1055  2020-12-05
49   San Diego County      88181    1047  2020-12-04
50   San Diego County      86142    1040  2020-12-03
51   San Diego County      84638    1035  2020-12-02
52   San Diego County      83421    1019  2020-12-01
53   San Diego County      82043     997  2020-11-30
54   San Diego County      81084     997  2020-11-29
55   San Diego County      80018     997  2020-11-28
56   San Diego County      78159     996  2020-11-27
57   San Diego County      75307     988  2020-11-26
58   San Diego County      75305     988  2020-11-25
59   San Diego County      74361     984  2020-11-24
60   San Diego County      72815     968  2020-11-23
61   San Diego County      71648     968  2020-11-22
62   San Diego County      70709     966  2020-11-21
63   San Diego County      69231     960  2020-11-20
64   San Diego County      68140     952  2020-11-19
65   San Diego County      67241     945  2020-11-18
66   San Diego County      66319     933  2020-11-17
67   San Diego County      65601     926  2020-11-16
68   San Diego County      64768     926  2020-11-15
69   San Diego County      63681     926  2020-11-14
70   San Diego County      62945     921  2020-11-13
71   San Diego County      62334     918  2020-11-12
72   San Diego County      61085     915  2020-11-11
73   San Diego County      61053     915  2020-11-10
74   San Diego County      60570     938  2020-11-09
75   San Diego County      60169     908  2020-11-08
76   San Diego County      59656     908  2020-11-07
77   San Diego County      59116     907  2020-11-06
78   San Diego County      58636     904  2020-11-05
79   San Diego County      58106     904  2020-11-04
80   San Diego County      57702     901  2020-11-03
81   San Diego County      57409     891  2020-11-02
82   San Diego County      57102     891  2020-11-01
83   San Diego County      56750     891  2020-10-31
84   San Diego County      56369     888  2020-10-30
85   San Diego County      55898     885  2020-10-29
86   San Diego County      55540     881  2020-10-28
87   San Diego County      55210     877  2020-10-27
88   San Diego County      54941     870  2020-10-26
89   San Diego County      54583     870  2020-10-25
90   San Diego County      54314     868  2020-10-24
91   San Diego County      53928     867  2020-10-23
92   San Diego County      53498     866  2020-10-22
93   San Diego County      53263     863  2020-10-21
94   San Diego County      53000     857  2020-10-20
95   San Diego County      52735     853  2020-10-19
96   San Diego County      52355     853  2020-10-18
97   San Diego County      51982     869  2020-10-17
98   San Diego County      51781     865  2020-10-16
99   San Diego County      51470     847  2020-10-15
100  San Diego County      51327     844  2020-10-14
101  San Diego County      51024     840  2020-10-13
102  San Diego County      50746     826  2020-10-12
103  San Diego County      50551     826  2020-10-11
104  San Diego County      50143     825  2020-10-10
105  San Diego County      49823     821  2020-10-09
106  San Diego County      49466     819  2020-10-08
107  San Diego County      49175     813  2020-10-07
108  San Diego County      48821     806  2020-10-06
109  San Diego County      48660     803  2020-10-05
110  San Diego County      48436     803  2020-10-04
111  San Diego County      48200     798  2020-10-03
112  San Diego County      47791     794  2020-10-02
113  San Diego County      47485     792  2020-10-01
114  San Diego County      47180     783  2020-09-30
115  San Diego County      46985     781  2020-09-29
116  San Diego County      46734     776  2020-09-28
117  San Diego County      46610     776  2020-09-27
118  San Diego County      46331     775  2020-09-26
119  San Diego County      46001     775  2020-09-25
120  San Diego County      45596     773  2020-09-24
121  San Diego County      45425     767  2020-09-23
122  San Diego County      45147     765  2020-09-22
123  San Diego County      44925     760  2020-09-21
124  San Diego County      44577     760  2020-09-20
125  San Diego County      44293     796  2020-09-19
126  San Diego County      44007     757  2020-09-18
127  San Diego County      43619     754  2020-09-17
128  San Diego County      43445     748  2020-09-16
129  San Diego County      43181     742  2020-09-15
130  San Diego County      42887     734  2020-09-14
131  San Diego County      42679     734  2020-09-13
132  San Diego County      42414     734  2020-09-12
133  San Diego County      41969     730  2020-09-11
134  San Diego County      41608     725  2020-09-10
135  San Diego County      41324     721  2020-09-09
136  San Diego County      40868     708  2020-09-08
137  San Diego County      40652     707  2020-09-07
138  San Diego County      40650     707  2020-09-06
139  San Diego County      40342     704  2020-09-05
140  San Diego County      39899     701  2020-09-04
141  San Diego County      39446     700  2020-09-03
142  San Diego County      39121     695  2020-09-02
143  San Diego County      38871     688  2020-09-01
144  San Diego County      38604     682  2020-08-31
145  San Diego County      38300     682  2020-08-30
146  San Diego County      38047     679  2020-08-29
147  San Diego County      37784     676  2020-08-28
148  San Diego County      37499     673  2020-08-27
149  San Diego County      37222     668  2020-08-26
150  San Diego County      36994     665  2020-08-25
151  San Diego County      36727     660  2020-08-24
152  San Diego County      36540     660  2020-08-23
153  San Diego County      36203     660  2020-08-22
154  San Diego County      35912     652  2020-08-21
155  San Diego County      35608     644  2020-08-20
156  San Diego County      35376     638  2020-08-19
157  San Diego County      34960     626  2020-08-18
158  San Diego County      34678     626  2020-08-17
159  San Diego County      34344     626  2020-08-16
160  San Diego County      34065     622  2020-08-15
161  San Diego County      34065     622  2020-08-14
162  San Diego County      33393     608  2020-08-13
163  San Diego County      33157     602  2020-08-12
164  San Diego County      32975     594  2020-08-11
165  San Diego County      32975     594  2020-08-10
166  San Diego County      32330     593  2020-08-09
167  San Diego County      31779     586  2020-08-08
168  San Diego County      31127     583  2020-08-07
169  San Diego County      31127     583  2020-08-06
170  San Diego County      30516     568  2020-08-05
171  San Diego County      30516     568  2020-08-04
172  San Diego County      29883     565  2020-08-03
173  San Diego County      29883     565  2020-08-02
174  San Diego County      29048     561  2020-08-01
175  San Diego County      29048     561  2020-07-31
176  San Diego County      28688     558  2020-07-30
177  San Diego County      28287     552  2020-07-29
178  San Diego County      27507     533  2020-07-28
179  San Diego County      27507     533  2020-07-27
180  San Diego County      26701     533  2020-07-26
181  San Diego County      26098     524  2020-07-25
182  San Diego County      26098     524  2020-07-24
183  San Diego County      25608     512  2020-07-23
184  San Diego County      25107     505  2020-07-22
185  San Diego County      24520     487  2020-07-21
186  San Diego County      24135     478  2020-07-20
187  San Diego County      23682     478  2020-07-19
188  San Diego County      23114     478  2020-07-18
189  San Diego County      21855     465  2020-07-17
190  San Diego County      21855     465  2020-07-16
191  San Diego County      21446     448  2020-07-15
192  San Diego County      20887     436  2020-07-14
193  San Diego County      19929     422  2020-07-13
194  San Diego County      19371     422  2020-07-12
195  San Diego County      19371     422  2020-07-11
196  San Diego County      18863     420  2020-07-10
197  San Diego County      18402     415  2020-07-09
198  San Diego County      17842     406  2020-07-08
199  San Diego County      17578     399  2020-07-07
200  San Diego County      16726     387  2020-07-06
201  San Diego County      16726     387  2020-07-05
202  San Diego County      15696     387  2020-07-04
203  San Diego County      15696     387  2020-07-03
204  San Diego County      15207     377  2020-07-02
205  San Diego County      14623     370  2020-07-01
206  San Diego County      14149     365  2020-06-30
207  San Diego County      13832     361  2020-06-29
208  San Diego County      13334     361  2020-06-28
209  San Diego County      12837     360  2020-06-27
210  San Diego County      12401     358  2020-06-26
211  San Diego County      11961     352  2020-06-25
212  San Diego County      11626     347  2020-06-24
213  San Diego County      11294     341  2020-06-23
214  San Diego County      11096     338  2020-06-22
215  San Diego County      10794     338  2020-06-21
216  San Diego County      10484     338  2020-06-20
217  San Diego County      10350     332  2020-06-19
218  San Diego County      10092     331  2020-06-18
219  San Diego County       9730     323  2020-06-17
220  San Diego County       9730     323  2020-06-16
221  San Diego County       9610     320  2020-06-15
222  San Diego County       9440     319  2020-06-14
223  San Diego County       9314     319  2020-06-13
224  San Diego County       8998     308  2020-06-12
225  San Diego County       8998     308  2020-06-11
226  San Diego County       8837     305  2020-06-10
227  San Diego County       8619     296  2020-06-09
228  San Diego County       8619     296  2020-06-08
229  San Diego County       8345     296  2020-06-07
230  San Diego County       8345     296  2020-06-06
231  San Diego County       7940     288  2020-06-05
232  San Diego County       7798     283  2020-06-04
233  San Diego County       7674     276  2020-06-03
234  San Diego County       7554     269  2020-06-02
235  San Diego County       7481     269  2020-06-01
236  San Diego County       7481     269  2020-05-31
237  San Diego County       7385     269  2020-05-30
238  San Diego County       7100     260  2020-05-29
239  San Diego County       7100     260  2020-05-28
240  San Diego County       6882     249  2020-05-27
241  San Diego County       6797     249  2020-05-26
242  San Diego County       6701     249  2020-05-25
243  San Diego County       6559     249  2020-05-24
244  San Diego County       6559     249  2020-05-23
245  San Diego County       6315     241  2020-05-22
246  San Diego County       6140     230  2020-05-21
247  San Diego County       6140     230  2020-05-20
248  San Diego County       6026     222  2020-05-19
249  San Diego County       5836     209  2020-05-18
250  San Diego County       5836     209  2020-05-17
251  San Diego County       5662     209  2020-05-16
252  San Diego County       5391     200  2020-05-15
253  San Diego County       5391     200  2020-05-14
254  San Diego County       5161     190  2020-05-13
255  San Diego County       5161     190  2020-05-12
256  San Diego County       5065     175  2020-05-11
257  San Diego County       4776     175  2020-05-10
258  San Diego County       4662     169  2020-05-09
259  San Diego County       4429     165  2020-05-08
260  San Diego County       4319     158  2020-05-07
261  San Diego County       4319     158  2020-05-06
262  San Diego County       4020     144  2020-05-05
263  San Diego County       3927     139  2020-05-04
264  San Diego County       3927     139  2020-05-03
265  San Diego County       3711     134  2020-05-02
266  San Diego County       3564     124  2020-05-01
267  San Diego County       3432     120  2020-04-30
268  San Diego County       3432     120  2020-04-29
269  San Diego County       3141     113  2020-04-28
270  San Diego County       3043     111  2020-04-27
271  San Diego County       2943     111  2020-04-26
272  San Diego County       2943     111  2020-04-25
273  San Diego County       2826     102  2020-04-24
274  San Diego County       2643     100  2020-04-23
275  San Diego County       2491      96  2020-04-22
276  San Diego County       2325      72  2020-04-21
277  San Diego County       2268      71  2020-04-20
278  San Diego County       2213      71  2020-04-19
279  San Diego County       2158      70  2020-04-18
280  San Diego County       2087      63  2020-04-17
281  San Diego County       2012      60  2020-04-16
282  San Diego County       1930      53  2020-04-15
283  San Diego County       1847      47  2020-04-14
284  San Diego County       1804      45  2020-04-13
285  San Diego County       1761      45  2020-04-12
286  San Diego County       1693      44  2020-04-11
287  San Diego County       1628      40  2020-04-10
288  San Diego County       1530      36  2020-04-09
289  San Diego County       1454      31  2020-04-08
290  San Diego County       1404      19  2020-04-07
291  San Diego County       1326      19  2020-04-06
292  San Diego County       1209      18  2020-04-05
293  San Diego County       1112      17  2020-04-04
294  San Diego County        966      16  2020-04-03
295  San Diego County        849      15  2020-04-02
296  San Diego County        733       9  2020-04-01
297  San Diego County        603       7  2020-03-31
298  San Diego County        515       7  2020-03-30
299  San Diego County        484       7  2020-03-29
300  San Diego County        413       6  2020-03-28
301  San Diego County        341       3  2020-03-27
302  San Diego County        293       3  2020-03-26
303  San Diego County        238       2  2020-03-25
304  San Diego County        226       1  2020-03-24
305  San Diego County        201       1  2020-03-23
306  San Diego County        155       0  2020-03-22
307  San Diego County        127       0  2020-03-21
308  San Diego County        127       0  2020-03-20
309  San Diego County         80       0  2020-03-19
310  San Diego County         60       0  2020-03-18
311  San Diego County         55       0  2020-03-17
312  San Diego County         55       0  2020-03-16
313  San Diego County         16       0  2020-03-15
314  San Diego County         10       0  2020-03-14
315  San Diego County          8       0  2020-03-13
316  San Diego County          5       0  2020-03-12
317  San Diego County          3       0  2020-03-11
318  San Diego County          3       0  2020-03-10
319  San Diego County          3       0  2020-03-09
320  San Diego County          3       0  2020-03-08
321  San Diego County          3       0  2020-03-07
322  San Diego County          3       0  2020-03-06
323  San Diego County          3       0  2020-03-05
324  San Diego County          2       0  2020-03-04
325  San Diego County          2       0  2020-03-03
326  San Diego County          2       0  2020-03-02
327  San Diego County          2       0  2020-03-01
328  San Diego County          2       0  2020-02-29
329  San Diego County          2       0  2020-02-28
330  San Diego County          2       0  2020-02-27
331  San Diego County          2       0  2020-02-26
332  San Diego County          2       0  2020-02-25
333  San Diego County          2       0  2020-02-24
334  San Diego County          2       0  2020-02-23
335  San Diego County          2       0  2020-02-22
336  San Diego County          2       0  2020-02-21
337  San Diego County          2       0  2020-02-20
338  San Diego County          2       0  2020-02-19
339  San Diego County          2       0  2020-02-18
340  San Diego County          2       0  2020-02-17
341  San Diego County          2       0  2020-02-16
342  San Diego County          2       0  2020-02-15
343  San Diego County          2       0  2020-02-14
344  San Diego County          2       0  2020-02-13
345  San Diego County          1       0  2020-02-12
346  San Diego County          1       0  2020-02-11

### COVID-19 Cases in San Diego Country by Zip code

Get lastest update day for SDHHSA data

In [9]:
query = """
MATCH (:PostalCode)<-[:REPORTED_IN]-(c:Cases{source: 'SDHHSA'}) 
RETURN max(c.date)  // returns a neotime.Date object
"""
date_sdhhsa = graph.evaluate(query).to_native() # convert to datetime.date object

In [10]:
query = """
MATCH (c:Cases{date: date($date), source: 'SDHHSA'})-[:REPORTED_IN]->(p:PostalCode)
RETURN p.name as zip, p.placeName, p.location, c.cases as confirmed, c.date as date
ORDER by zip
"""
graph.run(query, date=date_sdhhsa).to_data_frame()

       zip         p.placeName            p.location  confirmed        date
0    91901              Alpine  (-116.7543, 32.8282)       1004  2021-01-21
1    91902              Bonita  (-117.0221, 32.6671)       1091  2021-01-21
2    91905           Boulevard    (-116.32, 32.6719)         56  2021-01-21
3    91906               Campo  (-116.4905, 32.6605)        239  2021-01-21
4    91910         Chula Vista  (-117.0676, 32.6371)       7439  2021-01-21
5    91911         Chula Vista  (-117.0565, 32.6084)       9188  2021-01-21
6    91913         Chula Vista  (-116.9852, 32.6513)       3718  2021-01-21
7    91914         Chula Vista  (-116.9652, 32.6587)       1162  2021-01-21
8    91915         Chula Vista  (-116.9408, 32.6315)       2248  2021-01-21
9    91916            Descanso   (-116.6027, 32.873)         73  2021-01-21
10   91917             Dulzura  (-116.7285, 32.6152)        161  2021-01-21
11   91931              Guatay  (-116.5583, 32.8497)         10  2021-01-21
12   91932      Imperial Beach  (-117.1148, 32.5783)       2092  2021-01-21
13   91934             Jacumba  (-116.1952, 32.6249)         32  2021-01-21
14   91935               Jamul  (-116.8323, 32.7163)        519  2021-01-21
15   91941             La Mesa  (-117.0115, 32.7604)       1758  2021-01-21
16   91942             La Mesa  (-117.0189, 32.7835)       1948  2021-01-21
17   91945         Lemon Grove  (-117.0326, 32.7332)       2283  2021-01-21
18   91950       National City  (-117.0897, 32.6749)       6197  2021-01-21
19   91962         Pine Valley   (-116.5127, 32.835)         76  2021-01-21
20   91963             Potrero  (-116.6037, 32.6205)        168  2021-01-21
21   91977       Spring Valley   (-116.9976, 32.724)       5376  2021-01-21
22   91978       Spring Valley  (-116.9596, 32.7329)        663  2021-01-21
23   91980              Tecate  (-116.6192, 32.5889)        165  2021-01-21
24   92003             Bonsall   (-117.1897, 33.294)        222  2021-01-21
25   92004     Borrego Springs  (-116.3514, 33.2386)        118  2021-01-21
26   92007  Cardiff By The Sea   (-117.2745, 33.023)        295  2021-01-21
27   92008            Carlsbad   (-117.325, 33.1602)       1033  2021-01-21
28   92009            Carlsbad  (-117.2619, 33.0954)       1375  2021-01-21
29   92010            Carlsbad  (-117.3009, 33.1639)        616  2021-01-21
30   92011            Carlsbad  (-117.2943, 33.1072)        659  2021-01-21
31   92014             Del Mar   (-117.249, 32.9665)        333  2021-01-21
32   92019            El Cajon  (-116.9191, 32.7777)       3444  2021-01-21
33   92020            El Cajon  (-116.9665, 32.7928)       5470  2021-01-21
34   92021            El Cajon  (-116.9223, 32.8178)       5742  2021-01-21
35   92024           Encinitas  (-117.2689, 33.0535)       1800  2021-01-21
36   92025           Escondido    (-117.07, 33.1101)       4294  2021-01-21
37   92026           Escondido  (-117.0978, 33.1605)       3945  2021-01-21
38   92027           Escondido   (-117.052, 33.1388)       4899  2021-01-21
39   92028           Fallbrook    (-117.229, 33.369)       2885  2021-01-21
40   92029           Escondido  (-117.1128, 33.0895)       1105  2021-01-21
41   92036              Julian  (-116.5658, 33.0534)         79  2021-01-21
42   92037            La Jolla  (-117.2521, 32.8455)       1190  2021-01-21
43   92040            Lakeside  (-116.9201, 32.8562)       2299  2021-01-21
44   92054           Oceanside  (-117.3573, 33.2072)       2098  2021-01-21
45   92055      Camp Pendleton  (-117.3768, 33.2433)        447  2021-01-21
46   92056           Oceanside  (-117.2831, 33.1968)       2791  2021-01-21
47   92057           Oceanside  (-117.3025, 33.2407)       3300  2021-01-21
48   92058           Oceanside  (-117.3795, 33.1959)       1845  2021-01-21
49   92059                Pala  (-117.0717, 33.3777)        228  2021-01-21
50   92060    Palomar Mountain  (-116.8786, 33.3228)         15  2021-01-21
51   92061        Pauma Valley  (-116.9596, 33.3063)        177  2021-01-21
52   92064               Poway  (-117.0402, 32.9756)       1809  2021-01-21
53   92065              Ramona  (-116.8535, 33.0293)       1978  2021-01-21
54   92066            Ranchita    (-116.5167, 33.21)         12  2021-01-21
55   92067     Rancho Santa Fe   (-117.2157, 33.005)        290  2021-01-21
56   92069          San Marcos  (-117.1697, 33.1444)       3618  2021-01-21
57   92070        Santa Ysabel  (-116.6963, 33.1476)         53  2021-01-21
58   92071              Santee  (-116.9862, 32.8486)       2841  2021-01-21
59   92075        Solana Beach  (-117.2598, 32.9937)        359  2021-01-21
60   92078          San Marcos   (-117.185, 33.1193)       2563  2021-01-21
61   92081               Vista  (-117.2403, 33.1644)       1461  2021-01-21
62   92082       Valley Center   (-117.0122, 33.249)       1155  2021-01-21
63   92083               Vista  (-117.2482, 33.1978)       3544  2021-01-21
64   92084               Vista  (-117.2243, 33.2131)       3865  2021-01-21
65   92086      Warner Springs  (-116.6527, 33.3096)         48  2021-01-21
66   92091     Rancho Santa Fe  (-117.0462, 32.9623)         29  2021-01-21
67   92093            La Jolla  (-117.2742, 32.8473)        148  2021-01-21
68   92096          San Marcos  (-117.1661, 33.1434)          5  2021-01-21
69   92101           San Diego  (-117.1593, 32.7185)       3177  2021-01-21
70   92102           San Diego  (-117.1219, 32.7139)       3556  2021-01-21
71   92103           San Diego  (-117.1636, 32.7466)       1423  2021-01-21
72   92104           San Diego  (-117.1272, 32.7454)       2174  2021-01-21
73   92105           San Diego  (-117.0947, 32.7423)       5589  2021-01-21
74   92106           San Diego  (-117.2268, 32.7272)        605  2021-01-21
75   92107           San Diego  (-117.2433, 32.7425)        885  2021-01-21
76   92108           San Diego  (-117.1335, 32.7783)       1248  2021-01-21
77   92109           San Diego  (-117.2405, 32.7969)       2316  2021-01-21
78   92110           San Diego  (-117.2028, 32.7635)       1290  2021-01-21
79   92111           San Diego  (-117.1708, 32.7972)       2352  2021-01-21
80   92113           San Diego   (-117.1153, 32.697)       5878  2021-01-21
81   92114           San Diego  (-117.0524, 32.7059)       5632  2021-01-21
82   92115           San Diego  (-117.0721, 32.7607)       4623  2021-01-21
83   92116           San Diego  (-117.1242, 32.7624)       1309  2021-01-21
84   92117           San Diego  (-117.1965, 32.8239)       2269  2021-01-21
85   92118            Coronado  (-117.1698, 32.6807)        541  2021-01-21
86   92119           San Diego  (-117.0261, 32.8036)        955  2021-01-21
87   92120           San Diego  (-117.0707, 32.7958)       1322  2021-01-21
88   92121           San Diego  (-117.2035, 32.8919)        144  2021-01-21
89   92122           San Diego  (-117.2115, 32.8577)       1030  2021-01-21
90   92123           San Diego  (-117.1392, 32.7973)       1711  2021-01-21
91   92124           San Diego  (-117.0986, 32.8201)        925  2021-01-21
92   92126           San Diego  (-117.1402, 32.9161)       3126  2021-01-21
93   92127           San Diego  (-117.0856, 33.0279)       1286  2021-01-21
94   92128           San Diego   (-117.069, 33.0067)       1611  2021-01-21
95   92129           San Diego  (-117.1213, 32.9652)       1514  2021-01-21
96   92130           San Diego  (-117.2252, 32.9555)       1350  2021-01-21
97   92131           San Diego  (-117.0898, 32.9123)        967  2021-01-21
98   92134           San Diego  (-117.1466, 32.7242)         34  2021-01-21
99   92135           San Diego  (-117.1573, 32.7153)         73  2021-01-21
100  92136           San Diego  (-117.1219, 32.6834)        170  2021-01-21
101  92139           San Diego  (-117.0474, 32.6806)       2776  2021-01-21
102  92140           San Diego  (-117.2004, 32.7434)        105  2021-01-21
103  92145           San Diego  (-117.1005, 32.8891)         12  2021-01-21
104  92154           San Diego  (-117.0707, 32.5753)      11616  2021-01-21
105  92155           San Diego  (-117.1657, 32.6716)         15  2021-01-21
106  92173          San Ysidro   (-117.043, 32.5626)       5438  2021-01-21
107  92182           San Diego  (-117.0762, 32.7751)         21  2021-01-21
108  92536             Aguanga  (-116.7997, 33.4473)          5  2021-01-21
109  92672        San Clemente  (-117.6231, 33.4361)         43  2021-01-21

### COVID 19 Cases Time Series for Carlsbad, California
Cases are aggregated from the zip-level data (note, some zip code areas may cross city boundaries)

In [11]:
query = """
MATCH (c:Cases{source: 'SDHHSA'})-[:REPORTED_IN]->(p:PostalCode{placeName:'Carlsbad'})-[:IN*]->(a:Admin1{name: 'California'})
RETURN c.date as date, sum(c.cases) as confirmed
ORDER by date DESC
"""
graph.run(query).to_data_frame()

           date  confirmed
0    2021-01-21       3683
1    2021-01-20       3650
2    2021-01-19       3613
3    2021-01-18       3588
4    2021-01-16       3505
5    2021-01-15       3479
6    2021-01-14       3436
7    2021-01-13       3379
8    2021-01-12       3334
9    2021-01-11       3292
10   2021-01-10       3236
11   2021-01-09       3191
12   2021-01-08       3141
13   2021-01-07       3078
14   2021-01-06       2970
15   2021-01-05       2897
16   2021-01-04       2827
17   2021-01-03       2801
18   2021-01-02       2760
19   2021-01-01       2699
20   2020-12-31       2621
21   2020-12-30       2550
22   2020-12-29       2486
23   2020-12-28       2442
24   2020-12-27       2414
25   2020-12-26       2384
26   2020-12-25       2331
27   2020-12-24       2280
28   2020-12-23       2224
29   2020-12-22       2173
30   2020-12-21       2110
31   2020-12-20       2073
32   2020-12-19       2005
33   2020-12-18       1950
34   2020-12-17       1905
35   2020-12-16       1853
36   2020-12-15       1817
37   2020-12-14       1771
38   2020-12-13       1730
39   2020-12-12       1682
40   2020-12-11       1651
41   2020-12-10       1605
42   2020-12-09       1556
43   2020-12-08       1530
44   2020-12-07       1495
45   2020-12-06       1467
46   2020-12-05       1440
47   2020-12-04       1421
48   2020-12-03       1381
49   2020-12-02       1347
50   2020-12-01       1311
51   2020-11-30       1290
52   2020-11-29       1262
53   2020-11-28       1252
54   2020-11-27       1231
55   2020-11-26       1205
56   2020-11-25       1176
57   2020-11-24       1157
58   2020-11-23       1139
59   2020-11-22       1113
60   2020-11-21       1097
61   2020-11-20       1081
62   2020-11-19       1062
63   2020-11-18       1046
64   2020-11-17       1031
65   2020-11-16       1016
66   2020-11-15       1005
67   2020-11-14        994
68   2020-11-13        981
69   2020-11-12        974
70   2020-11-11        968
71   2020-11-10        960
72   2020-11-09        947
73   2020-11-08        943
74   2020-11-07        935
75   2020-11-06        924
76   2020-11-05        910
77   2020-11-04        906
78   2020-11-03        892
79   2020-11-02        888
80   2020-11-01        882
81   2020-10-31        881
82   2020-10-30        874
83   2020-10-29        869
84   2020-10-28        855
85   2020-10-27        852
86   2020-10-26        841
87   2020-10-25        838
88   2020-10-24        832
89   2020-10-23        830
90   2020-10-22        822
91   2020-10-21        815
92   2020-10-20        808
93   2020-10-19        801
94   2020-10-18        794
95   2020-10-17        787
96   2020-10-16        780
97   2020-10-15        777
98   2020-10-14        772
99   2020-10-13        769
100  2020-10-12        766
101  2020-10-11        763
102  2020-10-10        761
103  2020-10-09        756
104  2020-10-08        754
105  2020-10-07        749
106  2020-10-06        742
107  2020-10-05        731
108  2020-10-04        726
109  2020-10-03        724
110  2020-10-02        720
111  2020-10-01        717
112  2020-09-30        710
113  2020-09-29        704
114  2020-09-28        700
115  2020-09-27        699
116  2020-09-26        701
117  2020-09-25        696
118  2020-09-24        696
119  2020-09-23        692
120  2020-09-22        691
121  2020-09-21        685
122  2020-09-20        679
123  2020-09-19        680
124  2020-09-18        674
125  2020-09-17        670
126  2020-09-16        668
127  2020-09-15        670
128  2020-09-14        668
129  2020-09-13        663
130  2020-09-12        657
131  2020-09-11        653
132  2020-09-10        643
133  2020-09-09        640
134  2020-09-08        639
135  2020-09-07        638
136  2020-09-06        629
137  2020-09-05        627
138  2020-09-04        621
139  2020-09-03        611
140  2020-09-02        602
141  2020-09-01        597
142  2020-08-31        599
143  2020-08-30        595
144  2020-08-29        593
145  2020-08-28        591
146  2020-08-27        585
147  2020-08-26        584
148  2020-08-25        575
149  2020-08-24        574
150  2020-08-23        573
151  2020-08-22        568
152  2020-08-21        561
153  2020-08-20        559
154  2020-08-19        557
155  2020-08-18        555
156  2020-08-17        555
157  2020-08-16        552
158  2020-08-15        551
159  2020-08-14        543
160  2020-08-13        537
161  2020-08-12        533
162  2020-08-11        530
163  2020-08-10        524
164  2020-08-09        524
165  2020-08-08        521
166  2020-08-07        518
167  2020-08-06        516
168  2020-08-05        500
169  2020-08-04        499
170  2020-08-03        496
171  2020-08-02        489
172  2020-08-01        485
173  2020-07-31        485
174  2020-07-30        478
175  2020-07-29        472
176  2020-07-28        466
177  2020-07-27        452
178  2020-07-26        444
179  2020-07-25        439
180  2020-07-24        432
181  2020-07-23        424
182  2020-07-22        420
183  2020-07-21        412
184  2020-07-20        402
185  2020-07-19        395
186  2020-07-18        385
187  2020-07-17        380
188  2020-07-16        365
189  2020-07-15        345
190  2020-07-14        334
191  2020-07-13        325
192  2020-07-12        318
193  2020-07-11        311
194  2020-07-10        295
195  2020-07-09        285
196  2020-07-08        273
197  2020-07-07        267
198  2020-07-06        255
199  2020-07-05        246
200  2020-07-04        234
201  2020-07-03        217
202  2020-07-02        198
203  2020-07-01        191
204  2020-06-30        182
205  2020-06-29        167
206  2020-06-28        160
207  2020-06-27        155
208  2020-06-26        149
209  2020-06-25        139
210  2020-06-24        136
211  2020-06-23        127
212  2020-06-22        122
213  2020-06-21        115
214  2020-06-20        111
215  2020-06-19        104
216  2020-06-18        103
217  2020-06-17         98
218  2020-06-16         96
219  2020-06-15         93
220  2020-06-14         92
221  2020-06-13         90
222  2020-06-12         89
223  2020-06-11         88
224  2020-06-10         86
225  2020-06-09         85
226  2020-06-08         86
227  2020-06-07         85
228  2020-06-06         84
229  2020-06-05         84
230  2020-06-04         82
231  2020-06-03         80
232  2020-06-02         77
233  2020-06-01         77
234  2020-05-31         77
235  2020-05-30         76
236  2020-05-29         76
237  2020-05-28         76
238  2020-05-27         75
239  2020-05-26         75
240  2020-05-25         73
241  2020-05-24         73
242  2020-05-23         73
243  2020-05-22         73
244  2020-05-21         73
245  2020-05-20         72
246  2020-05-19         71
247  2020-05-18         71
248  2020-05-17         71
249  2020-05-16         71
250  2020-05-15         70
251  2020-05-14         69
252  2020-05-13         69
253  2020-05-12         66
254  2020-05-11         63
255  2020-05-10         63
256  2020-05-09         61
257  2020-05-08         58
258  2020-05-07         58
259  2020-05-06         58
260  2020-05-05         57
261  2020-05-04         57
262  2020-05-03         56
263  2020-05-02         56
264  2020-05-01         56
265  2020-04-30         56
266  2020-04-29         54
267  2020-04-28         52
268  2020-04-27         51
269  2020-04-26         50
270  2020-04-25         50
271  2020-04-24         50
272  2020-04-23         50
273  2020-04-22         50
274  2020-04-21         50
275  2020-04-20         50
276  2020-04-19         50
277  2020-04-18         50
278  2020-04-17         50
279  2020-04-16         50
280  2020-04-15         50
281  2020-04-14         50
282  2020-04-13         49
283  2020-04-12         48
284  2020-04-11         48
285  2020-04-10         48
286  2020-04-09         48
287  2020-04-08         43
288  2020-04-07         43
289  2020-04-06         42
290  2020-04-05         42
291  2020-04-04         42
292  2020-04-03         41
293  2020-04-02         39
294  2020-04-01         37
295  2020-03-31         32
296  2020-03-30         31

### COVID-19 cases aggregated by US Regions
Here we aggregate US county-level data over 2 hops:

`Admin2 -> USDivision -> USRegion`

using the variable-length relationship [:IN*].

In [12]:
query = """
MATCH (c:Cases{date: date($date), source: 'JHU'})-[:REPORTED_IN]->(:Admin2)-[:IN*]->(u:USRegion)
RETURN sum(c.cases) AS count, u.name AS USRegion
ORDER by count DESC
"""
graph.run(query, date=date).to_data_frame()

     count          USRegion
0  9533817      South Region
1  5709329       West Region
2  5543101    Midwest Region
3  3662754  Northeast Region

### COVID-19 cases aggregated by UN Region
Here we aggregate country-level data over up to 3 hops:

`country -> UNSubRegion -> UNIntermediateRegion -> UNRegion`

using the variable-length relationship `[:IN*`].

In [13]:
query = """
MATCH (c:Cases{date: date($date), source: 'JHU'})-[:REPORTED_IN]->(:Country)-[:IN*]->(u:UNRegion)
RETURN sum(c.cases) AS count, u.name AS UNRegion
ORDER by count DESC
"""
df = graph.run(query, date=date).to_data_frame()
df

      count  UNRegion
0  42827946  Americas
1  28659580    Europe
2  22397619      Asia
3   3406952    Africa
4     21087   Oceania

In [14]:
print("Total number of confirmed cases:", df['count'].sum())

Total number of confirmed cases: 97313184