# Example queries for Case Counts on COVID-19 Knowledge Graph
[Work in progress]

This notebook demonstrates how to run Cypher queries to retrieve and aggregate COVID-19 case counts.

COVID-19 case numbers are provided by:

Country and US County level data: [JHU](https://github.com/covid-19-net/covid-19-community/blob/master/reference_data/DataProvider.csv#L6)

San Diego data by zip code: [SDHHSA](https://github.com/covid-19-net/covid-19-community/blob/master/reference_data/DataProvider.csv#L7)

In [1]:
import datetime
import pandas as pd
from py2neo import Graph

In [2]:
pd.options.display.max_rows = None  # display all rows
pd.options.display.max_columns = None  # display all columsns

#### Connect to COVID-19-Net Knowledge Graph

In [3]:
graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")

In [4]:
# currently defining "yesterday" as two days from current date, 
# since there are time periods during the day, where data from the 
# previous day are not yet available in UTC date.
today = datetime.datetime.utcnow().date()
yesterday = today - datetime.timedelta(days=1)

## COVID Case Data

### Case counts by Country (using Johns Hopkins COVID-19 data)

In [5]:
query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(n:Country)
RETURN n.name, c.cases, c.deaths, c.date as date
ORDER by n.name
"""
graph.run(query, day=yesterday).to_data_frame()

                               n.name  c.cases  c.deaths        date
0                         Afghanistan    41032      1523  2020-10-27
1                             Albania    19729       487  2020-10-27
2                             Algeria    56706      1931  2020-10-27
3                             Andorra     4410        72  2020-10-27
4                              Angola     9871       271  2020-10-27
5                            Anguilla        3         0  2020-10-27
6                 Antigua and Barbuda      124         3  2020-10-27
7                           Argentina  1116609     29730  2020-10-27
8                             Armenia    80410      1222  2020-10-27
9                               Aruba     4437        36  2020-10-27
10                            Austria    86102      1005  2020-10-27
11                         Azerbaijan    51149       688  2020-10-27
12                            Bahamas     6502       136  2020-10-27
13                            Bahrain    80765       316  2020-10-27
14                         Bangladesh   401586      5838  2020-10-27
15                           Barbados      233         7  2020-10-27
16                            Belarus    94609       965  2020-10-27
17                            Belgium   333718     10899  2020-10-27
18                             Belize     3200        51  2020-10-27
19                              Benin     2557        41  2020-10-27
20                            Bermuda      194         9  2020-10-27
21                             Bhutan      345         0  2020-10-27
22                            Bolivia   141124      8672  2020-10-27
23             Bosnia and Herzegovina    43151      1125  2020-10-27
24                           Botswana     6283        21  2020-10-27
25                             Brazil  5439641    157946  2020-10-27
26             British Virgin Islands       71         1  2020-10-27
27                             Brunei      148         3  2020-10-27
28                           Bulgaria    42701      1161  2020-10-27
29                       Burkina Faso     2466        67  2020-10-27
30                            Burundi      558         1  2020-10-27
31                         Cabo Verde     8472        94  2020-10-27
32                           Cambodia      290         0  2020-10-27
33                           Cameroon    21793       426  2020-10-27
34                     Cayman Islands      239         1  2020-10-27
35           Central African Republic     4863        62  2020-10-27
36                               Chad     1460        96  2020-10-27
37                              Chile   504525     14026  2020-10-27
38                           Colombia  1033218     30565  2020-10-27
39                            Comoros      517         7  2020-10-27
40                         Costa Rica   105322      1329  2020-10-27
41                            Croatia    38621       470  2020-10-27
42                               Cuba     6678       128  2020-10-27
43                            Curacao      884         1  2020-10-27
44                             Cyprus     3817        25  2020-10-27
45                            Czechia   284033      2547  2020-10-27
46   Democratic Republic of the Congo    11191       305  2020-10-27
47                            Denmark    42157       709  2020-10-27
48                           Djibouti     5544        61  2020-10-27
49                           Dominica       38         0  2020-10-27
50                 Dominican Republic   125008      2226  2020-10-27
51                            Ecuador   163192     12588  2020-10-27
52                              Egypt   106877      6222  2020-10-27
53                        El Salvador    32925       957  2020-10-27
54                  Equatorial Guinea     5083        83  2020-10-27
55                            Eritrea      461         0  2020-10-27
56                            Estonia     4465        73  2020-10-27
57                           Eswatini     5875       116  2020-10-27
58                           Ethiopia    94218      1445  2020-10-27
59                   Falkland Islands       13         0  2020-10-27
60                      Faroe Islands      494         0  2020-10-27
61                               Fiji       33         2  2020-10-27
62                            Finland    15163       354  2020-10-27
63                             France  1206014     35268  2020-10-27
64                      French Guiana    10397        70  2020-10-27
65                   French Polynesia     6431        26  2020-10-27
66                              Gabon     8937        54  2020-10-27
67                             Gambia     3666       119  2020-10-27
68                            Georgia    32127       238  2020-10-27
69                            Germany   463419     10121  2020-10-27
70                              Ghana    47775       316  2020-10-27
71                          Gibraltar      679         0  2020-10-27
72                             Greece    32752       593  2020-10-27
73                          Greenland       17         0  2020-10-27
74                            Grenada       28         0  2020-10-27
75                         Guadeloupe     7474       115  2020-10-27
76                          Guatemala   105571      3665  2020-10-27
77                           Guernsey      822        48  2020-10-27
78                             Guinea    11819        71  2020-10-27
79                      Guinea-Bissau     2403        41  2020-10-27
80                             Guyana     4061       119  2020-10-27
81                              Haiti     9040       232  2020-10-27
82                           Honduras    94623      2639  2020-10-27
83                          Hong Kong     5308       105  2020-10-27
84                            Hungary    63642      1535  2020-10-27
85                            Iceland     4574        11  2020-10-27
86                              India  7946429    119502  2020-10-27
87                          Indonesia   396454     13512  2020-10-27
88                               Iran   581824     33299  2020-10-27
89                               Iraq   459908     10724  2020-10-27
90                            Ireland    58767      1890  2020-10-27
91                        Isle of Man      352        24  2020-10-27
92                             Israel   311724      2483  2020-10-27
93                              Italy   564778     37700  2020-10-27
94                        Ivory Coast    20488       122  2020-10-27
95                            Jamaica     8787       196  2020-10-27
96                              Japan    98146      1726  2020-10-27
97                             Jordan    58855       668  2020-10-27
98                         Kazakhstan   110832      1825  2020-10-27
99                              Kenya    50833       934  2020-10-27
100                            Kosovo    17943       663  2020-10-27
101                            Kuwait   123092       756  2020-10-27
102                        Kyrgyzstan    56738      1136  2020-10-27
103                              Laos       24         0  2020-10-27
104                            Latvia     4893        63  2020-10-27
105                           Lebanon    73995       590  2020-10-27
106                           Lesotho     1947        43  2020-10-27
107                           Liberia     1419        82  2020-10-27
108                             Libya    57975       812  2020-10-27
109                     Liechtenstein      428         1  2020-10-27
110                         Lithuania    11362       141  2020-10-27
111                        Luxembourg    14884       147  2020-10-27
112                        Madagascar    16968       244  2020-10-27
113                            Malawi     5897       183  2020-10-27
114                          Malaysia    28640       238  2020-10-27
115                          Maldives    11567        37  2020-10-27
116                              Mali     3515       136  2020-10-27
117                             Malta     5685        55  2020-10-27
118                        Martinique     3552        30  2020-10-27
119                        Mauritania     7680       163  2020-10-27
120                         Mauritius      439        10  2020-10-27
121                           Mayotte     4321        44  2020-10-27
122                            Mexico   901268     89814  2020-10-27
123                           Moldova    72460      1710  2020-10-27
124                            Monaco      320         2  2020-10-27
125                          Mongolia      340         0  2020-10-27
126                        Montenegro    17091       275  2020-10-27
127                        Montserrat       13         1  2020-10-27
128                           Morocco   203733      3445  2020-10-27
129                        Mozambique    12273        89  2020-10-27
130                           Myanmar    47666      1147  2020-10-27
131                           Namibia    12729       133  2020-10-27
132                             Nepal   160400       876  2020-10-27
133                       Netherlands   311889      7142  2020-10-27
134                     New Caledonia       27         0  2020-10-27
135                       New Zealand     1943        25  2020-10-27
136                         Nicaragua     5514       156  2020-10-27
137                             Niger     1218        69  2020-10-27
138                           Nigeria    62224      1135  2020-10-27
139                   North Macedonia    27827       949  2020-10-27
140                            Norway    18666       280  2020-10-27
141                              Oman   113820      1203  2020-10-27
142                          Pakistan   330200      6759  2020-10-27
143             Palestinian Territory    51528       458  2020-10-27
144                            Panama   130422      2650  2020-10-27
145                  Papua New Guinea      588         7  2020-10-27
146                          Paraguay    60557      1347  2020-10-27
147                              Peru   890574     34197  2020-10-27
148                       Philippines   373144      7053  2020-10-27
149                            Poland   280229      4615  2020-10-27
150                          Portugal   124432      2371  2020-10-27
151                             Qatar   131689       230  2020-10-27
152             Republic of the Congo     5253        92  2020-10-27
153                           Reunion     5361        20  2020-10-27
154                           Romania   217216      6574  2020-10-27
155                            Russia  1537142     26409  2020-10-27
156                            Rwanda     5084        35  2020-10-27
157                  Saint Barthelemy       83         0  2020-10-27
158             Saint Kitts and Nevis       19         0  2020-10-27
159                       Saint Lucia       65         0  2020-10-27
160                      Saint Martin      566         9  2020-10-27
161         Saint Pierre and Miquelon       16         0  2020-10-27
162  Saint Vincent and the Grenadines       74         0  2020-10-27
163                        San Marino      852        42  2020-10-27
164             Sao Tome and Principe      941        15  2020-10-27
165                      Saudi Arabia   345631      5329  2020-10-27
166                           Senegal    15571       322  2020-10-27
167                            Serbia    40880       798  2020-10-27
168                        Seychelles      153         0  2020-10-27
169                      Sierra Leone     2350        74  2020-10-27
170                         Singapore    57980        28  2020-10-27
171                      Sint Maarten      792        22  2020-10-27
172                          Slovakia    46056       176  2020-10-27
173                          Slovenia    25603       264  2020-10-27
174                   Solomon Islands        8         0  2020-10-27
175                           Somalia     3941       104  2020-10-27
176                      South Africa   717851     19053  2020-10-27
177                       South Korea    26146       461  2020-10-27
178                       South Sudan     2890        56  2020-10-27
179                             Spain  1116738     35298  2020-10-27
180                         Sri Lanka     8870        19  2020-10-27
181                             Sudan    13747       837  2020-10-27
182                          Suriname     5187       111  2020-10-27
183                            Sweden   115785      5918  2020-10-27
184                       Switzerland   127042      2147  2020-10-27
185                             Syria     5528       275  2020-10-27
186                            Taiwan      550         7  2020-10-27
187                        Tajikistan    10860        81  2020-10-27
188                          Tanzania      509        21  2020-10-27
189                          Thailand     3759        59  2020-10-27
190                       Timor Leste       30         0  2020-10-27
191                              Togo     2229        54  2020-10-27
192               Trinidad and Tobago     5568       106  2020-10-27
193                           Tunisia    52399       983  2020-10-27
194                            Turkey   366208      9950  2020-10-27
195          Turks and Caicos Islands      703         6  2020-10-27
196                            Uganda    11621       103  2020-10-27
197                           Ukraine   366233      6770  2020-10-27
198              United Arab Emirates   127624       482  2020-10-27
199                    United Kingdom   917575     45365  2020-10-27
200                     United States  8777432    226691  2020-10-27
201                           Uruguay     2916        54  2020-10-27
202                        Uzbekistan    65881       556  2020-10-27
203                           Vatican       27         0  2020-10-27
204                         Venezuela    90400       780  2020-10-27
205                           Vietnam     1172        35  2020-10-27
206                    Western Sahara       10         1  2020-10-27
207                             Yemen     2060       599  2020-10-27
208                            Zambia    16243       348  2020-10-27
209                          Zimbabwe     8315       242  2020-10-27

### Case counts by US States aggregated from US Counties
Note, some counties in the Johns Hopkins dataset cannot be mapped to US counties. They are listed in as "None"

In [6]:
query = """
MATCH (c:Cases{date: $date, source: 'JHU'})-[:REPORTED_IN]->(a:Admin2)-[:IN]->(a1:Admin1)
RETURN a1.name as state, a1.code, a1.location, sum(c.deaths) as deaths, sum(c.cases) as confirmed, c.date as date
ORDER BY a1.code
"""
graph.run(query, date=yesterday).to_data_frame()

,state,a1.code,a1.location,deaths,confirmed,date
0,Alaska,AK,"(-150.00028, 64.00028)",70,14736,2020-10-27
1,Alabama,AL,"(-86.75026, 32.75041)",2892,186437,2020-10-27
2,Arkansas,AR,"(-92.50044, 34.75037)",1857,105581,2020-10-27
3,Arizona,AZ,"(-111.50098, 34.5003)",5890,240121,2020-10-27
4,California,CA,"(-119.75126, 37.25022)",17460,914888,2020-10-27
5,Colorado,CO,"(-105.50083, 39.00027)",2236,98710,2020-10-27
6,Connecticut,CT,"(-72.66648, 41.66704)",4595,68484,2020-10-27
7,District of Columbia,DC,"(-77.00025, 38.91706)",644,16906,2020-10-27
8,Delaware,DE,"(-75.49992, 39.00039)",686,24158,2020-10-27
9,Florida,FL,"(-82.5001, 28.75054)",16505,784455,2020-10-27
10,Georgia,GA,"(-83.50018, 32.75042)",7656,336791,2020-10-27
11,Hawaii,HI,"(-156.38612, 20.78785)",214,14715,2020-10-27
12,Iowa,IA,"(-93.50049, 42.00027)",1680,118548,2020-10-27
13,Idaho,ID,"(-114.25118, 44.5002)",585,60923,2020-10-27
14,Illinois,IL,"(-89.25037, 40.00032)",9568,382902,2020-10-27
15,Indiana,IN,"(-86.25027, 40.00032)",3958,166564,2020-10-27
16,Kansas,KS,"(-98.50063, 38.50029)",983,77887,2020-10-27
17,Kentucky,KY,"(-84.87762, 38.20042)",1428,99637,2020-10-27
18,Louisiana,LA,"(-92.0004, 31.00047)",5666,180684,2020-10-27
19,Massachusetts,MA,"(-71.10832, 42.36565)",9881,148812,2020-10-27
20,Maryland,MD,"(-76.74997, 39.00039)",4095,141741,2020-10-27
21,Maine,ME,"(-69.24977, 45.50032)",146,6309,2020-10-27
22,Michigan,MI,"(-85.50033, 44.25029)",7502,175219,2020-10-27
23,Minnesota,MN,"(-94.25055, 46.25024)",2368,137343,2020-10-27
24,Missouri,MO,"(-92.50046, 38.25031)",2659,160695,2020-10-27
25,Mississippi,MS,"(-89.75036, 32.75041)",3283,116617,2020-10-27
26,Montana,MT,"(-109.75102, 47.00025)",305,29346,2020-10-27
27,North Carolina,NC,"(-80.00032, 35.50069)",4211,263883,2020-10-27
28,North Dakota,ND,"(-100.00068, 47.50027)",476,39130,2020-10-27
29,Nebraska,NE,"(-99.75067, 41.50028)",617,64915,2020-10-27
30,New Hampshire,NH,"(-71.4998, 43.66702)",475,10509,2020-10-27
31,New Jersey,NJ,"(-74.49987, 40.16706)",16306,230851,2020-10-27
32,New Mexico,NM,"(-106.00085, 34.50034)",980,41464,2020-10-27
33,Nevada,NV,"(-116.75119, 39.25021)",1752,96908,2020-10-27
34,New York,NY,"(-75.4999, 43.00035)",33412,498646,2020-10-27
35,Ohio,OH,"(-83.00018, 40.25034)",5239,202740,2020-10-27
36,Oklahoma,OK,"(-97.50328, 35.49209)",1273,118403,2020-10-27
37,Oregon,OR,"(-120.50139, 44.00013)",664,42808,2020-10-27
38,Pennsylvania,PA,"(-77.7, 40.8)",8683,203520,2020-10-27
39,Rhode Island,RI,"(-71.49978, 41.75038)",1152,26194,2020-10-27
40,South Carolina,SC,"(-81.00009, 34.00043)",3842,172579,2020-10-27
41,South Dakota,SD,"(-100.25069, 44.50026)",375,40730,2020-10-27
42,Tennessee,TN,"(-86.25027, 35.75035)",3167,245273,2020-10-27
43,Texas,TX,"(-99.25061, 31.25044)",18061,904769,2020-10-27
44,Utah,UT,"(-111.75103, 39.25024)",461,87291,2020-10-27
45,Virginia,VA,"(-77.44675, 37.54812)",3595,174786,2020-10-27
46,Vermont,VT,"(-72.74983, 44.00034)",58,2105,2020-10-27
47,Washington,WA,"(-120.50147, 47.50012)",2334,103662,2020-10-27
48,Wisconsin,WI,"(-90.00041, 44.50024)",1852,206311,2020-10-27
49,West Virginia,WV,"(-80.50009, 38.50038)",434,22710,2020-10-27
50,Wyoming,WY,"(-107.5009, 43.00024)",77,11806,2020-10-27

### Current cases in San Diego County

In [7]:
admin2 = 'San Diego County'

query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cases as confirmed, c.deaths as deaths, c.date as date
"""
graph.run(query, admin2=admin2, day=yesterday).to_data_frame()

               name  confirmed  deaths        date
0  San Diego County      55210     877  2020-10-27

### COVID-19 Cases Time Series in San Diego County

In [8]:
query = """
MATCH (c:Cases{source: 'JHU'})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cases as confirmed, c.deaths as deaths, c.date as date
ORDER BY c.date DESC
"""
graph.run(query, admin2=admin2).to_data_frame()

                 name  confirmed  deaths        date
0    San Diego County      55210     877  2020-10-27
1    San Diego County      54941     870  2020-10-26
2    San Diego County      54583     870  2020-10-25
3    San Diego County      54314     868  2020-10-24
4    San Diego County      53928     867  2020-10-23
5    San Diego County      53498     866  2020-10-22
6    San Diego County      53263     863  2020-10-21
7    San Diego County      53000     857  2020-10-20
8    San Diego County      52735     853  2020-10-19
9    San Diego County      52355     853  2020-10-18
10   San Diego County      51982     869  2020-10-17
11   San Diego County      51781     865  2020-10-16
12   San Diego County      51470     847  2020-10-15
13   San Diego County      51327     844  2020-10-14
14   San Diego County      51024     840  2020-10-13
15   San Diego County      50746     826  2020-10-12
16   San Diego County      50551     826  2020-10-11
17   San Diego County      50143     825  2020-10-10
18   San Diego County      49823     821  2020-10-09
19   San Diego County      49466     819  2020-10-08
20   San Diego County      49175     813  2020-10-07
21   San Diego County      48821     806  2020-10-06
22   San Diego County      48660     803  2020-10-05
23   San Diego County      48436     803  2020-10-04
24   San Diego County      48200     798  2020-10-03
25   San Diego County      47791     794  2020-10-02
26   San Diego County      47485     792  2020-10-01
27   San Diego County      47180     783  2020-09-30
28   San Diego County      46985     781  2020-09-29
29   San Diego County      46734     776  2020-09-28
30   San Diego County      46610     776  2020-09-27
31   San Diego County      46331     775  2020-09-26
32   San Diego County      46001     775  2020-09-25
33   San Diego County      45596     773  2020-09-24
34   San Diego County      45425     767  2020-09-23
35   San Diego County      45147     765  2020-09-22
36   San Diego County      44925     760  2020-09-21
37   San Diego County      44577     760  2020-09-20
38   San Diego County      44293     796  2020-09-19
39   San Diego County      44007     757  2020-09-18
40   San Diego County      43619     754  2020-09-17
41   San Diego County      43445     748  2020-09-16
42   San Diego County      43181     742  2020-09-15
43   San Diego County      42887     734  2020-09-14
44   San Diego County      42679     734  2020-09-13
45   San Diego County      42414     734  2020-09-12
46   San Diego County      41969     730  2020-09-11
47   San Diego County      41608     725  2020-09-10
48   San Diego County      41324     721  2020-09-09
49   San Diego County      40868     708  2020-09-08
50   San Diego County      40652     707  2020-09-07
51   San Diego County      40650     707  2020-09-06
52   San Diego County      40342     704  2020-09-05
53   San Diego County      39899     701  2020-09-04
54   San Diego County      39446     700  2020-09-03
55   San Diego County      39121     695  2020-09-02
56   San Diego County      38871     688  2020-09-01
57   San Diego County      38604     682  2020-08-31
58   San Diego County      38300     682  2020-08-30
59   San Diego County      38047     679  2020-08-29
60   San Diego County      37784     676  2020-08-28
61   San Diego County      37499     673  2020-08-27
62   San Diego County      37222     668  2020-08-26
63   San Diego County      36994     665  2020-08-25
64   San Diego County      36727     660  2020-08-24
65   San Diego County      36540     660  2020-08-23
66   San Diego County      36203     660  2020-08-22
67   San Diego County      35912     652  2020-08-21
68   San Diego County      35608     644  2020-08-20
69   San Diego County      35376     638  2020-08-19
70   San Diego County      34960     626  2020-08-18
71   San Diego County      34678     626  2020-08-17
72   San Diego County      34344     626  2020-08-16
73   San Diego County      34065     622  2020-08-15
74   San Diego County      34065     622  2020-08-14
75   San Diego County      33393     608  2020-08-13
76   San Diego County      33157     602  2020-08-12
77   San Diego County      32975     594  2020-08-11
78   San Diego County      32975     594  2020-08-10
79   San Diego County      32330     593  2020-08-09
80   San Diego County      31779     586  2020-08-08
81   San Diego County      31127     583  2020-08-07
82   San Diego County      31127     583  2020-08-06
83   San Diego County      30516     568  2020-08-05
84   San Diego County      30516     568  2020-08-04
85   San Diego County      29883     565  2020-08-03
86   San Diego County      29883     565  2020-08-02
87   San Diego County      29048     561  2020-08-01
88   San Diego County      29048     561  2020-07-31
89   San Diego County      28688     558  2020-07-30
90   San Diego County      28287     552  2020-07-29
91   San Diego County      27507     533  2020-07-28
92   San Diego County      27507     533  2020-07-27
93   San Diego County      26701     533  2020-07-26
94   San Diego County      26098     524  2020-07-25
95   San Diego County      26098     524  2020-07-24
96   San Diego County      25608     512  2020-07-23
97   San Diego County      25107     505  2020-07-22
98   San Diego County      24520     487  2020-07-21
99   San Diego County      24135     478  2020-07-20
100  San Diego County      23682     478  2020-07-19
101  San Diego County      23114     478  2020-07-18
102  San Diego County      21855     465  2020-07-17
103  San Diego County      21855     465  2020-07-16
104  San Diego County      21446     448  2020-07-15
105  San Diego County      20887     436  2020-07-14
106  San Diego County      19929     422  2020-07-13
107  San Diego County      19371     422  2020-07-12
108  San Diego County      19371     422  2020-07-11
109  San Diego County      18863     420  2020-07-10
110  San Diego County      18402     415  2020-07-09
111  San Diego County      17842     406  2020-07-08
112  San Diego County      17578     399  2020-07-07
113  San Diego County      16726     387  2020-07-06
114  San Diego County      16726     387  2020-07-05
115  San Diego County      15696     387  2020-07-04
116  San Diego County      15696     387  2020-07-03
117  San Diego County      15207     377  2020-07-02
118  San Diego County      14623     370  2020-07-01
119  San Diego County      14149     365  2020-06-30
120  San Diego County      13832     361  2020-06-29
121  San Diego County      13334     361  2020-06-28
122  San Diego County      12837     360  2020-06-27
123  San Diego County      12401     358  2020-06-26
124  San Diego County      11961     352  2020-06-25
125  San Diego County      11626     347  2020-06-24
126  San Diego County      11294     341  2020-06-23
127  San Diego County      11096     338  2020-06-22
128  San Diego County      10794     338  2020-06-21
129  San Diego County      10484     338  2020-06-20
130  San Diego County      10350     332  2020-06-19
131  San Diego County      10092     331  2020-06-18
132  San Diego County       9730     323  2020-06-17
133  San Diego County       9730     323  2020-06-16
134  San Diego County       9610     320  2020-06-15
135  San Diego County       9440     319  2020-06-14
136  San Diego County       9314     319  2020-06-13
137  San Diego County       8998     308  2020-06-12
138  San Diego County       8998     308  2020-06-11
139  San Diego County       8837     305  2020-06-10
140  San Diego County       8619     296  2020-06-09
141  San Diego County       8619     296  2020-06-08
142  San Diego County       8345     296  2020-06-07
143  San Diego County       8345     296  2020-06-06
144  San Diego County       7940     288  2020-06-05
145  San Diego County       7798     283  2020-06-04
146  San Diego County       7674     276  2020-06-03
147  San Diego County       7554     269  2020-06-02
148  San Diego County       7481     269  2020-06-01
149  San Diego County       7481     269  2020-05-31
150  San Diego County       7385     269  2020-05-30
151  San Diego County       7100     260  2020-05-29
152  San Diego County       7100     260  2020-05-28
153  San Diego County       6882     249  2020-05-27
154  San Diego County       6797     249  2020-05-26
155  San Diego County       6701     249  2020-05-25
156  San Diego County       6559     249  2020-05-24
157  San Diego County       6559     249  2020-05-23
158  San Diego County       6315     241  2020-05-22
159  San Diego County       6140     230  2020-05-21
160  San Diego County       6140     230  2020-05-20
161  San Diego County       6026     222  2020-05-19
162  San Diego County       5836     209  2020-05-18
163  San Diego County       5836     209  2020-05-17
164  San Diego County       5662     209  2020-05-16
165  San Diego County       5391     200  2020-05-15
166  San Diego County       5391     200  2020-05-14
167  San Diego County       5161     190  2020-05-13
168  San Diego County       5161     190  2020-05-12
169  San Diego County       5065     175  2020-05-11
170  San Diego County       4776     175  2020-05-10
171  San Diego County       4662     169  2020-05-09
172  San Diego County       4429     165  2020-05-08
173  San Diego County       4319     158  2020-05-07
174  San Diego County       4319     158  2020-05-06
175  San Diego County       4020     144  2020-05-05
176  San Diego County       3927     139  2020-05-04
177  San Diego County       3927     139  2020-05-03
178  San Diego County       3711     134  2020-05-02
179  San Diego County       3564     124  2020-05-01
180  San Diego County       3432     120  2020-04-30
181  San Diego County       3432     120  2020-04-29
182  San Diego County       3141     113  2020-04-28
183  San Diego County       3043     111  2020-04-27
184  San Diego County       2943     111  2020-04-26
185  San Diego County       2943     111  2020-04-25
186  San Diego County       2826     102  2020-04-24
187  San Diego County       2643     100  2020-04-23
188  San Diego County       2491      96  2020-04-22
189  San Diego County       2325      72  2020-04-21
190  San Diego County       2268      71  2020-04-20
191  San Diego County       2213      71  2020-04-19
192  San Diego County       2158      70  2020-04-18
193  San Diego County       2087      63  2020-04-17
194  San Diego County       2012      60  2020-04-16
195  San Diego County       1930      53  2020-04-15
196  San Diego County       1847      47  2020-04-14
197  San Diego County       1804      45  2020-04-13
198  San Diego County       1761      45  2020-04-12
199  San Diego County       1693      44  2020-04-11
200  San Diego County       1628      40  2020-04-10
201  San Diego County       1530      36  2020-04-09
202  San Diego County       1454      31  2020-04-08
203  San Diego County       1404      19  2020-04-07
204  San Diego County       1326      19  2020-04-06
205  San Diego County       1209      18  2020-04-05
206  San Diego County       1112      17  2020-04-04
207  San Diego County        966      16  2020-04-03
208  San Diego County        849      15  2020-04-02
209  San Diego County        733       9  2020-04-01
210  San Diego County        603       7  2020-03-31
211  San Diego County        515       7  2020-03-30
212  San Diego County        484       7  2020-03-29
213  San Diego County        413       6  2020-03-28
214  San Diego County        341       3  2020-03-27
215  San Diego County        293       3  2020-03-26
216  San Diego County        238       2  2020-03-25
217  San Diego County        226       1  2020-03-24
218  San Diego County        201       1  2020-03-23
219  San Diego County        155       0  2020-03-22
220  San Diego County        127       0  2020-03-21
221  San Diego County        127       0  2020-03-20
222  San Diego County         80       0  2020-03-19
223  San Diego County         60       0  2020-03-18
224  San Diego County         55       0  2020-03-17
225  San Diego County         55       0  2020-03-16
226  San Diego County         16       0  2020-03-15
227  San Diego County         10       0  2020-03-14
228  San Diego County          8       0  2020-03-13
229  San Diego County          5       0  2020-03-12
230  San Diego County          3       0  2020-03-11
231  San Diego County          3       0  2020-03-10
232  San Diego County          3       0  2020-03-09
233  San Diego County          3       0  2020-03-08
234  San Diego County          3       0  2020-03-07
235  San Diego County          3       0  2020-03-06
236  San Diego County          3       0  2020-03-05
237  San Diego County          2       0  2020-03-04
238  San Diego County          2       0  2020-03-03
239  San Diego County          2       0  2020-03-02
240  San Diego County          2       0  2020-03-01
241  San Diego County          2       0  2020-02-29
242  San Diego County          2       0  2020-02-28
243  San Diego County          2       0  2020-02-27
244  San Diego County          2       0  2020-02-26
245  San Diego County          2       0  2020-02-25
246  San Diego County          2       0  2020-02-24
247  San Diego County          2       0  2020-02-23
248  San Diego County          2       0  2020-02-22
249  San Diego County          2       0  2020-02-21
250  San Diego County          2       0  2020-02-20
251  San Diego County          2       0  2020-02-19
252  San Diego County          2       0  2020-02-18
253  San Diego County          2       0  2020-02-17
254  San Diego County          2       0  2020-02-16
255  San Diego County          2       0  2020-02-15
256  San Diego County          2       0  2020-02-14
257  San Diego County          2       0  2020-02-13
258  San Diego County          1       0  2020-02-12
259  San Diego County          1       0  2020-02-11

### COVID-19 Cases in San Diego Country by Zip code
The latest data may show up with a delay. If no output is show, adjust the date to a day earlier using this format: `date('2020-06-21')`.

In [9]:
query = """
MATCH (c:Cases{date: date($day), source: 'SDHHSA'})-[:REPORTED_IN]->(p:PostalCode)
RETURN p.name as zip, p.placeName, p.location, c.cases as confirmed, c.date as date
ORDER by zip
"""
graph.run(query, day=yesterday).to_data_frame()

Empty DataFrame
Columns: []
Index: []

### COVID 19 Cases Time Series for Carlsbad, California
Cases are aggregated from the zip-level data (note, some zip code areas may cross city boundaries)

In [10]:
query = """
MATCH (c:Cases{source: 'SDHHSA'})-[:REPORTED_IN]->(p:PostalCode{placeName:'Carlsbad'})-[:IN*]->(a:Admin1{name: 'California'})
RETURN c.date as date, sum(c.cases) as confirmed
ORDER by date DESC
"""
graph.run(query).to_data_frame()

           date  confirmed
0    2020-10-26        841
1    2020-10-25        838
2    2020-10-24        832
3    2020-10-23        830
4    2020-10-22        822
5    2020-10-21        815
6    2020-10-20        808
7    2020-10-19        801
8    2020-10-18        794
9    2020-10-17        787
10   2020-10-16        780
11   2020-10-15        777
12   2020-10-14        772
13   2020-10-13        769
14   2020-10-12        766
15   2020-10-11        763
16   2020-10-10        761
17   2020-10-09        756
18   2020-10-08        754
19   2020-10-07        749
20   2020-10-06        742
21   2020-10-05        731
22   2020-10-04        726
23   2020-10-03        724
24   2020-10-02        720
25   2020-10-01        717
26   2020-09-30        710
27   2020-09-29        704
28   2020-09-28        700
29   2020-09-27        699
30   2020-09-26        701
31   2020-09-25        696
32   2020-09-24        696
33   2020-09-23        692
34   2020-09-22        691
35   2020-09-21        685
36   2020-09-20        679
37   2020-09-19        680
38   2020-09-18        674
39   2020-09-17        670
40   2020-09-16        668
41   2020-09-15        670
42   2020-09-14        668
43   2020-09-13        663
44   2020-09-12        657
45   2020-09-11        653
46   2020-09-10        643
47   2020-09-09        640
48   2020-09-08        639
49   2020-09-07        638
50   2020-09-06        629
51   2020-09-05        627
52   2020-09-04        621
53   2020-09-03        611
54   2020-09-02        602
55   2020-09-01        597
56   2020-08-31        599
57   2020-08-30        595
58   2020-08-29        593
59   2020-08-28        591
60   2020-08-27        585
61   2020-08-26        584
62   2020-08-25        575
63   2020-08-24        574
64   2020-08-23        573
65   2020-08-22        568
66   2020-08-21        561
67   2020-08-20        559
68   2020-08-19        557
69   2020-08-18        555
70   2020-08-17        555
71   2020-08-16        552
72   2020-08-15        551
73   2020-08-14        543
74   2020-08-13        537
75   2020-08-12        533
76   2020-08-11        530
77   2020-08-10        524
78   2020-08-09        524
79   2020-08-08        521
80   2020-08-07        518
81   2020-08-06        516
82   2020-08-05        500
83   2020-08-04        499
84   2020-08-03        496
85   2020-08-02        489
86   2020-08-01        485
87   2020-07-31        485
88   2020-07-30        478
89   2020-07-29        472
90   2020-07-28        466
91   2020-07-27        452
92   2020-07-26        444
93   2020-07-25        439
94   2020-07-24        432
95   2020-07-23        424
96   2020-07-22        420
97   2020-07-21        412
98   2020-07-20        402
99   2020-07-19        395
100  2020-07-18        385
101  2020-07-17        380
102  2020-07-16        365
103  2020-07-15        345
104  2020-07-14        334
105  2020-07-13        325
106  2020-07-12        318
107  2020-07-11        311
108  2020-07-10        295
109  2020-07-09        285
110  2020-07-08        273
111  2020-07-07        267
112  2020-07-06        255
113  2020-07-05        246
114  2020-07-04        234
115  2020-07-03        217
116  2020-07-02        198
117  2020-07-01        191
118  2020-06-30        182
119  2020-06-29        167
120  2020-06-28        160
121  2020-06-27        155
122  2020-06-26        149
123  2020-06-25        139
124  2020-06-24        136
125  2020-06-23        127
126  2020-06-22        122
127  2020-06-21        115
128  2020-06-20        111
129  2020-06-19        104
130  2020-06-18        103
131  2020-06-17         98
132  2020-06-16         96
133  2020-06-15         93
134  2020-06-14         92
135  2020-06-13         90
136  2020-06-12         89
137  2020-06-11         88
138  2020-06-10         86
139  2020-06-09         85
140  2020-06-08         86
141  2020-06-07         85
142  2020-06-06         84
143  2020-06-05         84
144  2020-06-04         82
145  2020-06-03         80
146  2020-06-02         77
147  2020-06-01         77
148  2020-05-31         77
149  2020-05-30         76
150  2020-05-29         76
151  2020-05-28         76
152  2020-05-27         75
153  2020-05-26         75
154  2020-05-25         73
155  2020-05-24         73
156  2020-05-23         73
157  2020-05-22         73
158  2020-05-21         73
159  2020-05-20         72
160  2020-05-19         71
161  2020-05-18         71
162  2020-05-17         71
163  2020-05-16         71
164  2020-05-15         70
165  2020-05-14         69
166  2020-05-13         69
167  2020-05-12         66
168  2020-05-11         63
169  2020-05-10         63
170  2020-05-09         61
171  2020-05-08         58
172  2020-05-07         58
173  2020-05-06         58
174  2020-05-05         57
175  2020-05-04         57
176  2020-05-03         56
177  2020-05-02         56
178  2020-05-01         56
179  2020-04-30         56
180  2020-04-29         54
181  2020-04-28         52
182  2020-04-27         51
183  2020-04-26         50
184  2020-04-25         50
185  2020-04-24         50
186  2020-04-23         50
187  2020-04-22         50
188  2020-04-21         50
189  2020-04-20         50
190  2020-04-19         50
191  2020-04-18         50
192  2020-04-17         50
193  2020-04-16         50
194  2020-04-15         50
195  2020-04-14         50
196  2020-04-13         49
197  2020-04-12         48
198  2020-04-11         48
199  2020-04-10         48
200  2020-04-09         48
201  2020-04-08         43
202  2020-04-07         43
203  2020-04-06         42
204  2020-04-05         42
205  2020-04-04         42
206  2020-04-03         41
207  2020-04-02         39
208  2020-04-01         37
209  2020-03-31         32
210  2020-03-30         31

### COVID-19 cases aggregated by US Regions
Here we aggregate US county-level data over 2 hops:

`Admin2 -> USDivision -> USRegion`

using the variable-length relationship [:IN*].

In [11]:
query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(:Admin2)-[:IN*]->(u:USRegion)
RETURN sum(c.cases) AS count, u.name AS USRegion
ORDER by count DESC
"""
graph.run(query, day=yesterday).to_data_frame()

     count          USRegion
0  3895410      South Region
1  1772984    Midwest Region
2  1757378       West Region
3  1195430  Northeast Region

### COVID-19 cases aggregated by UN Region
Here we aggregate country-level data over up to 3 hops:

`country -> UNSubRegion -> UNIntermediateRegion -> UNRegion`

using the variable-length relationship `[:IN*`].

In [12]:
query = """
MATCH (c:Cases{date: date($day), source: 'JHU'})-[:REPORTED_IN]->(:Country)-[:IN*]->(u:UNRegion)
RETURN sum(c.cases) AS count, u.name AS UNRegion
ORDER by count DESC
"""
df = graph.run(query, day=yesterday).to_data_frame()
df

      count  UNRegion
0  19799899  Americas
1  13186291      Asia
2   8824410    Europe
3   1747522    Africa
4      9030   Oceania

In [13]:
print("Total number of confirmed cases:", df['count'].sum())

Total number of confirmed cases: 43567152