# Example queries for biological entities on COVID-19 Knowledge Graph
[Work in progress]

This notebook demonstrates how to run Cypher queries in a Jupyter Notebook by connecting to a database server.

In [1]:
import datetime
import pandas as pd
from py2neo import Graph

In [2]:
pd.options.display.max_rows = None  # display all rows
pd.options.display.max_columns = None  # display all columsns

In [3]:
graph = Graph("bolt://132.249.238.185:7687", user="reader", password="demo")

### List Node Metadata

In [4]:
query = """
MATCH (n:NodeMetadata)
RETURN n.name, n.shortDescription, n.description, n.example, n.details
"""
graph.run(query).to_data_frame()

,n.name,n.shortDescription,n.description,n.example,n.details
0,Location,Geographic location,A geograpic location,"World, ..., Country, State, Country, City, Cru...",None
1,World,The World,Top level location,None,None
2,UNRegion,Continental regions,Continental regions according to the M49 stan...,Americas,https://unstats.un.org/unsd/methodology/m49/
3,UNSubRegion,Subcontinental regions,Subcontinental regions according to the M49 st...,Latin America and the Caribbean,https://unstats.un.org/unsd/methodology/m49/
4,UNIntermediateRegion,Subdivisions of subcontinental regions,Subdivisions of subcontinental regions accordi...,Caribbean,https://unstats.un.org/unsd/methodology/m49/
5,Country,Countries and dependent Territories,Countries and dependent Territories defined b...,United States,http://www.geonames.org/
6,Admin1,"State, Province, Municipality","First administrative divisions, e.g, State, Pr...",California,http://www.geonames.org/
7,Admin2,County,Second administrative divisions: County in the US,San Diego County,http://www.geonames.org/
8,City,City,City,San Diego,http://www.geonames.org/
9,CruiseShip,Cruise ship,Cruise ship,Diamond Princess,http://www.productontology.org/doc/Cruise_ship
10,USRegion,Regions of the US,Regions defined by the US Census Bureau,West Region,https://www.census.gov/geographies/reference-f...
11,USDivision,Subregions of US,Divisions defined by the US Census Burea,Pacific Division,https://www.census.gov/geographies/reference-f...
12,Cases,Case counts,Number of case for outbreaks or diseases at sp...,COVID-19-YYYYMMDD,None
13,Outbreak,Increase in disease occurance,Statistically significant increase in disease ...,COVID-19,http://purl.obolibrary.org/obo/IDO_0000502
14,Organism,Living system,"Individual living system, such as animal, plan...",Homo sapiens,http://purl.obolibrary.org/obo/OBI_0100026
15,Host,Host organism for a virus,A host organism provides an environment suppor...,Homo sapiens,http://purl.obolibrary.org/obo/IDO_0000531
16,Pathogen,Diseae causing organism,"A bacterium, virus, or other microorganism tha...",SARS-CoV-2,http://purl.obolibrary.org/obo/IDO_0000528
17,Strain,Genetic variant of an organism,A population of organisms that is geneticaly d...,COVID-19 strain,https://semanticscience.org/resource/SIO_01005...
18,Clade,Group of organisms based on common ancestors,An identifier that denotes a group of organism...,SARS-CoV-2 A,http://purl.obolibrary.org/obo/APOLLO_SV_00000232
19,Gene,Sequence of nucleotides,Sequence of nucleotides in DNA or RNA that enc...,SARS-CoV-2 S gene,http://purl.obolibrary.org/obo/SO_0000704
20,Protein,Sequence of amino acids,Proteins are large biomolecules consisting of ...,Spike protein,http://purl.obolibrary.org/obo/SO_0000104
21,Publication,Published document,A document that has been accepted by a publisher,None,http://purl.obolibrary.org/obo/IAO_0000311

### List Organisms in KG

In [5]:
query = """
MATCH (p:Organism)
RETURN p.name as name, p.scientificName as scientificName, p.id as taxonomy
"""
graph.run(query).to_data_frame()

                          name scientificName          taxonomy
0                   SARS-CoV-2           None  taxonomy:2697049
1                     MERS-CoV           None  taxonomy:1335626
2                     SARS-CoV           None   taxonomy:694009
3                        human           None     taxonomy:9606
4                  house mouse           None    taxonomy:10090
5   intermediate horseshoe bat           None    taxonomy:59477
6        Malayan horseshoe bat           None   taxonomy:608659
7                horseshoe bat           None    taxonomy:49442
8             Malayan pangolin           None     taxonomy:9974
9                   palm civet           None    taxonomy:71116
10                  carnivores           None     taxonomy:9608
11                         cat           None     taxonomy:9685
12               European mink           None     taxonomy:9666
13               Malayan tiger           None   taxonomy:419130

### List Coronavirus Outbreaks

In [6]:
query = """
MATCH (p:Pathogen)-[:CAUSES]->(o:Outbreak)
RETURN p.name as name, p.scientificName as scientificName, p.id as taxonomy, o.id as outbreak, o.startDate as startDate
"""
graph.run(query).to_data_frame()

         name scientificName          taxonomy  outbreak startDate
0  SARS-CoV-2           None  taxonomy:2697049  COVID-19      2019
1    MERS-CoV           None  taxonomy:1335626      MERS      2012
2    SARS-CoV           None   taxonomy:694009      SARS      2003

### List Strains that are mentioned in PubMed Central Articles

In [7]:
query = """
MATCH (p:Publication)-[:MENTIONS]->(s:Strain)<-[:CARRIES]-(h:Host)
RETURN p.id as pmc, s.name as name, s.collectionDate  as collectionDate, h.name as host, h.id as host_id
ORDER by s.collectionDate
"""
graph.run(query).to_data_frame().head(20)

,pmc,name,collectionDate,host,host_id
0,pmc:PMC7166309,BetaCoV/pangolin/Guangxi/P1E/2017,2017-01-01,Malayan pangolin,taxonomy:9974
1,pmc:PMC7166309,BetaCoV/pangolin/Guangxi/P4L/2017,2017-01-01,Malayan pangolin,taxonomy:9974
2,pmc:PMC7166309,BetaCoV/pangolin/Guangxi/P5E/2017,2017-01-01,Malayan pangolin,taxonomy:9974
3,pmc:PMC7166309,BetaCoV/pangolin/Guangxi/P2V/2017,2017-01-01,Malayan pangolin,taxonomy:9974
4,pmc:PMC7166309,BetaCoV/pangolin/Guangxi/P5L/2017,2017-01-01,Malayan pangolin,taxonomy:9974
5,pmc:PMC7228214,BetaCoV/pangolin/Guangxi/P4L/2017,2017-01-01,Malayan pangolin,taxonomy:9974
6,pmc:PMC7166309,BetaCoV/pangolin/Guandong/1/2020,2019-01-01,Malayan pangolin,taxonomy:9974
7,pmc:PMC7228214,BetaCoV/pangolin/Guandong/1/2020,2019-01-01,Malayan pangolin,taxonomy:9974
8,pmc:PMC7205519,BetaCoV/pangolin/Guandong/1/2020,2019-01-01,Malayan pangolin,taxonomy:9974
9,pmc:PMC7256558,hCoV-19/bat/Yunnan/RmYN02/2019,2019-06-25,Malayan horseshoe bat,taxonomy:608659
10,pmc:PMC7118541,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
11,pmc:PMC7140597,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
12,pmc:PMC7132116,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
13,pmc:PMC7220294,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
14,pmc:PMC7245191,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
15,pmc:PMC7166773,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
16,pmc:PMC7157939,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
17,pmc:PMC7228331,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
18,pmc:PMC7227586,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606
19,pmc:PMC7171442,Wuhan-Hu-1,2019-12-10,human,taxonomy:9606

### List Gene and Protein information for Reference Genome
This query lists the genes and proteins encoded by the SARS-CoV-2 reference genome. This is the first genome of SARS-CoV-2 collected in Wuhan on Dec. 5, 2019.

In [8]:
query = """
MATCH (s:Strain)-[:HAS]->(g:Gene)-[:ENCODES]->(p:Protein)
RETURN s.id as referenceGenome, s.name as name, s.collectionDate  as collectionDate, 
       g.name as gene, g.id as geneId, p.name as protein, p.id as protein_id 
ORDER by s.collectionDate
"""
graph.run(query).to_data_frame()

,referenceGenome,name,collectionDate,gene,geneId,protein,protein_id
0,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-266-21555,Replicase polyprotein 1ab,md5:e6608b50fcd6e004708a875615ddf2d9
1,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-266-13483,Replicase polyprotein 1a,md5:e781b58591b8dbdd15f84dcbdec82105
2,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,S,ncbigene:43740568-21563-25384,Spike glycoprotein,md5:4c35f09aac2f7be4f3cffd30c6aecac8
3,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF3a,ncbigene:43740569-25393-26220,Protein 3a,md5:f5c8b89ceac3f14e456577557df1ef40
4,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,E,ncbigene:43740570-26245-26472,Envelope small membrane protein,md5:375e0f905c315e06a99c80b736c125d2
5,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,M,ncbigene:43740571-26523-27191,Membrane protein,md5:1cd6abff79ad3633e17582eb0e576539
6,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF6,ncbigene:43740572-27202-27387,Non-structural protein 6,md5:90b50e0be9abd893bd32b163d6933f0c
7,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF7a,ncbigene:43740573-27394-27759,Protein 7a,md5:f65213344e2e68de1cae4feb9c5e07b1
8,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF7b,ncbigene:43740574-27756-27887,Protein non-structural 7b,md5:c7f0179da4ca26456ee905081f485cc8
9,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF8,ncbigene:43740577-27894-28259,Non-structural protein 8,md5:3a77ad9207d29beacfbf6f18b0da9e26
10,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,N,ncbigene:43740575-28274-29533,Nucleoprotein,md5:b100d0849c3e01fc6c75ead0e916ce0f
11,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF10,ncbigene:43740576-29558-29674,ORF10 protein,md5:06bfef85cf1319e805e05f5bee3ec601
12,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-266-805,Host translation inhibitor nsp1,md5:5c2c364f44079728c451280435c4236a
13,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-806-2719,Non-structural protein 2,md5:073edb2349ddcd9a72ecd9f5c1dccdc4
14,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-2720-8554,Non-structural protein 3,md5:73935ca55d0ab6130627210ef6743c39
15,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-8555-10054,Non-structural protein 4,md5:6890e7e8e12f73c2dfdae6805ebc9c4f
16,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-10055-10972,3C-like proteinase,md5:dc6436f559bc873ac013085f6e56d467
17,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-10973-11842,Non-structural protein 6,md5:99424071c355c54269f6cd3522680033
18,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-11843-12091,Non-structural protein 7,md5:173be79f5a6fd85a7edb5c75cdc41fa3
19,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-12092-12685,Non-structural protein 8,md5:92ebecdcff1a59d6123f4e3133264695
20,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-12686-13024,Non-structural protein 9,md5:8c32758bc2f4b49ed8c6dfe7caa7ea49
21,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-13025-13441,Non-structural protein 10,md5:af0cec59296f3c845a7b04500cd6886b
22,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-13442-16236,RNA-directed RNA polymerase,md5:b88e641d00c17a3ce19cc9852c37717c
23,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-16237-18039,Helicase,md5:a489cf148afc7205eec14549ffe4ebfd
24,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-18040-19620,Proofreading exoribonuclease,md5:96fda12ecf3dcfec082377cc27e80e55
25,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-19621-20658,Uridylate-specific endoribonuclease,md5:d7d018de059ea6b8c092267ff6371d38
26,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-20659-21552,2'-O-methyltransferase,md5:42b973dceb72cdea04fda203c55b67bc
27,ncbiprotein:NC_045512,Wuhan-Hu-1,2019-12-10,ORF1ab,ncbigene:43740578-13442-13480,Non-structural protein 11,md5:63d2c81f37726f44c600eb5225676a66

## List COVID Case Data

### Cases in a specific County (Admin2)

#### At a specific date

In [9]:
today = datetime.datetime.utcnow().date()
yesterday = today - datetime.timedelta(days=1)

In [10]:
admin2 = 'San Diego County'

query = """
MATCH (c:Cases{date: date($day)})-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cummulativeConfirmed as confirmed, c.cummulativeDeaths as deaths, c.date as dateUTC
"""
graph.run(query, admin2=admin2, day=yesterday).to_data_frame()

               name  confirmed  deaths     dateUTC
0  San Diego County       8619     296  2020-06-09

##### All available dates

In [11]:
query = """
MATCH (c:Cases)-[:REPORTED_IN]->(a:Admin2{name: $admin2})
RETURN a.name as name, c.cummulativeConfirmed as confirmed, c.cummulativeDeaths as deaths, c.date as dateUTC
ORDER BY c.date DESC
"""
graph.run(query, admin2=admin2).to_data_frame()

                 name  confirmed  deaths     dateUTC
0    San Diego County       8619     296  2020-06-09
1    San Diego County       8619     296  2020-06-08
2    San Diego County       8345     296  2020-06-07
3    San Diego County       8345     296  2020-06-06
4    San Diego County       7940     288  2020-06-05
5    San Diego County       7798     283  2020-06-04
6    San Diego County       7674     276  2020-06-03
7    San Diego County       7554     269  2020-06-02
8    San Diego County       7481     269  2020-06-01
9    San Diego County       7481     269  2020-05-31
10   San Diego County       7385     269  2020-05-30
11   San Diego County       7100     260  2020-05-29
12   San Diego County       7100     260  2020-05-28
13   San Diego County       6882     249  2020-05-27
14   San Diego County       6797     249  2020-05-26
15   San Diego County       6701     249  2020-05-25
16   San Diego County       6559     249  2020-05-24
17   San Diego County       6559     249  2020-05-23
18   San Diego County       6315     241  2020-05-22
19   San Diego County       6140     230  2020-05-21
20   San Diego County       6140     230  2020-05-20
21   San Diego County       6026     222  2020-05-19
22   San Diego County       5836     209  2020-05-18
23   San Diego County       5836     209  2020-05-17
24   San Diego County       5662     209  2020-05-16
25   San Diego County       5391     200  2020-05-15
26   San Diego County       5391     200  2020-05-14
27   San Diego County       5161     190  2020-05-13
28   San Diego County       5161     190  2020-05-12
29   San Diego County       5065     175  2020-05-11
30   San Diego County       4776     175  2020-05-10
31   San Diego County       4662     169  2020-05-09
32   San Diego County       4429     165  2020-05-08
33   San Diego County       4319     158  2020-05-07
34   San Diego County       4319     158  2020-05-06
35   San Diego County       4020     144  2020-05-05
36   San Diego County       3927     139  2020-05-04
37   San Diego County       3927     139  2020-05-03
38   San Diego County       3711     134  2020-05-02
39   San Diego County       3564     124  2020-05-01
40   San Diego County       3432     120  2020-04-30
41   San Diego County       3432     120  2020-04-29
42   San Diego County       3141     113  2020-04-28
43   San Diego County       3043     111  2020-04-27
44   San Diego County       2943     111  2020-04-26
45   San Diego County       2943     111  2020-04-25
46   San Diego County       2826     102  2020-04-24
47   San Diego County       2643     100  2020-04-23
48   San Diego County       2491      96  2020-04-22
49   San Diego County       2325      72  2020-04-21
50   San Diego County       2268      71  2020-04-20
51   San Diego County       2213      71  2020-04-19
52   San Diego County       2158      70  2020-04-18
53   San Diego County       2087      63  2020-04-17
54   San Diego County       2012      60  2020-04-16
55   San Diego County       1930      53  2020-04-15
56   San Diego County       1847      47  2020-04-14
57   San Diego County       1804      45  2020-04-13
58   San Diego County       1761      45  2020-04-12
59   San Diego County       1693      44  2020-04-11
60   San Diego County       1628      40  2020-04-10
61   San Diego County       1530      36  2020-04-09
62   San Diego County       1454      31  2020-04-08
63   San Diego County       1404      19  2020-04-07
64   San Diego County       1326      19  2020-04-06
65   San Diego County       1209      18  2020-04-05
66   San Diego County       1112      17  2020-04-04
67   San Diego County        966      16  2020-04-03
68   San Diego County        849      15  2020-04-02
69   San Diego County        733       9  2020-04-01
70   San Diego County        603       7  2020-03-31
71   San Diego County        515       7  2020-03-30
72   San Diego County        484       7  2020-03-29
73   San Diego County        413       6  2020-03-28
74   San Diego County        341       3  2020-03-27
75   San Diego County        293       3  2020-03-26
76   San Diego County        238       2  2020-03-25
77   San Diego County        226       1  2020-03-24
78   San Diego County        201       1  2020-03-23
79   San Diego County        155       0  2020-03-22
80   San Diego County        127       0  2020-03-21
81   San Diego County        127       0  2020-03-20
82   San Diego County         80       0  2020-03-19
83   San Diego County         60       0  2020-03-18
84   San Diego County         55       0  2020-03-17
85   San Diego County         55       0  2020-03-16
86   San Diego County         16       0  2020-03-15
87   San Diego County         10       0  2020-03-14
88   San Diego County          8       0  2020-03-13
89   San Diego County          5       0  2020-03-12
90   San Diego County          3       0  2020-03-11
91   San Diego County          3       0  2020-03-10
92   San Diego County          3       0  2020-03-09
93   San Diego County          3       0  2020-03-08
94   San Diego County          3       0  2020-03-07
95   San Diego County          3       0  2020-03-06
96   San Diego County          3       0  2020-03-05
97   San Diego County          2       0  2020-03-04
98   San Diego County          2       0  2020-03-03
99   San Diego County          2       0  2020-03-02
100  San Diego County          2       0  2020-03-01
101  San Diego County          2       0  2020-02-29
102  San Diego County          2       0  2020-02-28
103  San Diego County          2       0  2020-02-27
104  San Diego County          2       0  2020-02-26
105  San Diego County          2       0  2020-02-25
106  San Diego County          2       0  2020-02-24
107  San Diego County          2       0  2020-02-23
108  San Diego County          2       0  2020-02-22
109  San Diego County          2       0  2020-02-21
110  San Diego County          2       0  2020-02-20
111  San Diego County          2       0  2020-02-19
112  San Diego County          2       0  2020-02-18
113  San Diego County          2       0  2020-02-17
114  San Diego County          2       0  2020-02-16
115  San Diego County          2       0  2020-02-15
116  San Diego County          2       0  2020-02-14
117  San Diego County          2       0  2020-02-13
118  San Diego County          1       0  2020-02-12
119  San Diego County          1       0  2020-02-11

### Aggregate cases by State (Admin1)

In [12]:
query = """
MATCH (o:Outbreak{id: "COVID-19"})<-[:RELATED_TO]-(c:Cases{date: $date})-[:REPORTED_IN]->(a:Admin2)-[:IN]->(a1:Admin1)
RETURN a1.name as state, sum(c.cummulativeDeaths) as deaths, sum(c.cummulativeConfirmed) as confirmed, c.date as dateUTC
ORDER BY deaths DESC
"""
graph.run(query, date=yesterday).to_data_frame()

             state  deaths  confirmed     dateUTC
0         New York   30458     379482  2020-06-09
1       New Jersey   12303     164541  2020-06-09
2    Massachusetts    7397     103534  2020-06-09
3     Pennsylvania    6014      80870  2020-06-09
4         Illinois    5919     127678  2020-06-09
5         Michigan    5821      60009  2020-06-09
6       California    4701     133848  2020-06-09
7      Connecticut    4097      43893  2020-06-09
8          Florida    2728      64951  2020-06-09
9             None    2554      51020  2020-06-09
10        Maryland    2450      51988  2020-06-09
11            Ohio    2423      39162  2020-06-09
12       Louisiana    2387      38091  2020-06-09
13         Georgia    2249      49478  2020-06-09
14         Indiana    2115      36596  2020-06-09
15           Texas    1867      78208  2020-06-09
16        Colorado    1553      28333  2020-06-09
17       Minnesota    1203      28318  2020-06-09
18        Virginia    1203      40246  2020-06-09
19      Washington    1176      24329  2020-06-09
20         Arizona    1074      28296  2020-06-09
21  North Carolina    1068      37227  2020-06-09
22     Mississippi     836      17481  2020-06-09
23         Alabama     723      20930  2020-06-09
24       Wisconsin     661      21201  2020-06-09
25            Iowa     626      22233  2020-06-09
26  South Carolina     568      15228  2020-06-09
27        Kentucky     477      11700  2020-06-09
28          Nevada     446      10045  2020-06-09
29       Tennessee     430      26948  2020-06-09
30        Delaware     410      10008  2020-06-09
31      New Mexico     400       7904  2020-06-09
32        Oklahoma     354       7363  2020-06-09
33   New Hampshire     286       5070  2020-06-09
34          Kansas     237      10609  2020-06-09
35        Nebraska     189      15701  2020-06-09
36          Oregon     169       4988  2020-06-09
37        Arkansas     160       9025  2020-06-09
38        Missouri     130       5501  2020-06-09
39            Utah     113      10603  2020-06-09
40           Maine     100       2604  2020-06-09
41           Idaho      85       3221  2020-06-09
42   West Virginia      84       2169  2020-06-09
43    North Dakota      72       2901  2020-06-09
44    South Dakota      68       5523  2020-06-09
45         Vermont      55       1079  2020-06-09
46         Montana      18        554  2020-06-09
47          Hawaii      17        670  2020-06-09
48          Alaska      11        571  2020-06-09
49         Wyoming       1        970  2020-06-09
50    Rhode Island       0      14077  2020-06-09